Repository hashicorp/terraform-provider-vault, pull requests merged in 2018-11, with the labels that each got.

#230 Check for 403s in kv_helper
  vault/kv_helpers.go
Labels: size/XS

#217 Use set connection_url when available instead of value read for API response
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/XS

#220 Add identity groups and aliases
  vault/provider.go
  vault/resource_identity_group.go
  vault/resource_identity_group_alias.go
  vault/resource_identity_group_alias_test.go
  vault/resource_identity_group_test.go
Labels: size/XL

#231 Fix link in database_secret_backend_connection resource
  website/docs/r/database_secret_backend_connection.md
Labels: size/XS

#235 Add simplify flag to gofmt
  GNUmakefile
  scripts/gofmtcheck.sh
  vault/resource_auth_backend.go
  vault/resource_gcp_auth_backend_role.go
  vault/resource_gcp_secret_backend.go
  vault/resource_ldap_auth_backend.go
Labels: size/XS

#236 Add Slack notifications for build failures
  .travis.yml
Labels: size/S

#198 Adding GCP Auth backend resource
  vault/provider.go
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_auth_backend_test.go
  website/docs/r/gcp_auth_backend.html.md
Labels: size/XL

#241 Fix resource name in docs menu
  website/vault.erb
Labels: size/XS

#240 remove wrong references in cert_auth_backend_role to gcp resources
  vault/resource_cert_auth_backend_role.go
Labels: size/XS

#242 Move utils to their own package
  util/util.go
  util/util_test.go
  vault/okta.go
  vault/resource_approle_auth_backend_login.go
  vault/resource_approle_auth_backend_role.go
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_identity_group.go
  vault/resource_jwt_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_ldap_auth_backend_group_test.go
  vault/resource_ldap_auth_backend_user.go
  vault/resource_ldap_auth_backend_user_test.go
  vault/resource_okta_auth_backend.go
  vault/resource_okta_auth_backend_group.go
  vault/resource_okta_auth_backend_test.go
  vault/resource_okta_auth_backend_user.go
  vault/util_test.go
Labels: size/L
