Repository hashicorp/terraform-provider-vault, pull requests merged in 2018-09, with the labels that each got.

#81 new resource: vault_audit
  vault/provider.go
  vault/resource_audit.go
  vault/resource_audit_test.go
Labels: new-resource, size/L

#153 Run testacc in CI, fix broken tests.
  .travis.yml
  vault/data_source_generic_secret_test.go
  vault/import_generic_secret_test.go
  vault/migrate_aws_auth_backend_role.go
  vault/migrate_aws_auth_backend_role_test.go
  vault/resource_auth_backend_test.go
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_tag_test.go
  vault/resource_aws_auth_backend_role_test.go
  vault/resource_generic_secret_test.go
  vault/resource_okta_auth_backend_test.go
  website/docs/r/aws_auth_backend_role.html.md
Labels: size/L

#123 New Resource: vault_cert_auth_backend_role
  vault/provider.go
  vault/resource_cert_auth_backend_role.go
  vault/resource_cert_auth_backend_role_test.go
  website/docs/r/cert_auth_backend_role.html.md
  website/vault.erb
Labels: size/XL

#59 Consul secret backend
  vault/import_consul_secret_backend_test.go
  vault/provider.go
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_test.go
  website/docs/r/consul_secret_backend.html.md
  website/vault.erb
Labels: new-resource, size/L

#126 New Resource: vault_ldap_auth_backend
  vault/provider.go
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_group.go
  vault/resource_ldap_auth_backend_group_test.go
  vault/resource_ldap_auth_backend_test.go
  vault/resource_ldap_auth_backend_user.go
  vault/resource_ldap_auth_backend_user_test.go
  vault/util.go
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/ldap_auth_backend_group.html.md
  website/docs/r/ldap_auth_backend_user.html.md
  website/vault.erb
Labels: size/XXL

#185 Revert "Run testacc in CI, fix broken tests."
  .travis.yml
  vault/data_source_generic_secret_test.go
  vault/import_generic_secret_test.go
  vault/migrate_aws_auth_backend_role.go
  vault/migrate_aws_auth_backend_role_test.go
  vault/resource_auth_backend_test.go
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_tag_test.go
  vault/resource_aws_auth_backend_role_test.go
  vault/resource_generic_secret_test.go
  vault/resource_okta_auth_backend_test.go
  website/docs/r/aws_auth_backend_role.html.md
Labels: size/XL

#186 Re-add "Run testacc in CI, fix broken tests."
  .travis.yml
  vault/data_source_generic_secret_test.go
  vault/import_generic_secret_test.go
  vault/migrate_aws_auth_backend_role.go
  vault/migrate_aws_auth_backend_role_test.go
  vault/resource_auth_backend_test.go
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_tag_test.go
  vault/resource_aws_auth_backend_role_test.go
  vault/resource_generic_secret_test.go
  vault/resource_okta_auth_backend_test.go
  website/docs/r/aws_auth_backend_role.html.md
Labels: size/XL

#87 add RDS, Aurora and legacy to MySQL backend
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: enhancement, size/L

#183 Update LDAP Documentation
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/ldap_auth_backend_group.html.md
  website/docs/r/ldap_auth_backend_user.html.md
Labels: size/S

#180 Add audit device resource documentation and make path optional
  vault/resource_audit.go
  website/docs/r/audit.html.md
  website/vault.erb
Labels: size/M

#181 docs/provider: Document resource import for remaining resources
  website/docs/r/aws_auth_backend_cert.html.md
  website/docs/r/aws_auth_backend_client.html.md
  website/docs/r/aws_auth_backend_identity_whitelist.html.md
  website/docs/r/aws_auth_backend_role.html.md
  website/docs/r/aws_auth_backend_sts_role.html.md
  website/docs/r/consul_secret_backend.html.md
  website/docs/r/database_secret_backend_connection.md
  website/docs/r/database_secret_backend_role.md
  website/docs/r/generic_secret.html.md
  website/docs/r/mount.html.md
  website/docs/r/policy.html.md
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/M

#188 add vault_jwt_auth_backend_role resource
  vault/provider.go
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  vault/util.go
  website/docs/r/jwt_auth_backend_role.md
  website/vault.erb
Labels: size/XL

#190 Update mount.html.md to have formatted code block.
  website/docs/r/mount.html.md
Labels: size/XS

#148 Do not return error in the case of an expired accessor
  vault/resource_approle_auth_backend_login.go
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/util.go
  vault/util_test.go
Labels: size/S

#184 Update `bindpass` in `vault_ldap_auth_backend`
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: size/XS
