Repository hashicorp/terraform-provider-vault, pull requests merged in 2018-10, with the labels that each got.

#163 Add SSH secret backend CA resource
  vault/provider.go
  vault/resource_ssh_secret_backend_ca.go
  vault/resource_ssh_secret_backend_ca_test.go
  website/docs/r/ssh_secret_backend_ca.html.md
  website/vault.erb
Labels: size/XL

#136 Fix #98: Support Vault token helper.
  vault/provider.go
  vault/provider_test.go
  vendor/github.com/armon/go-radix/go.mod
  vendor/github.com/armon/go-radix/radix.go
  vendor/github.com/hashicorp/vault/command/config/config.go
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mitchellh/cli/cli.go
  vendor/github.com/mitchellh/cli/go.mod
  vendor/github.com/mitchellh/cli/go.sum
  vendor/github.com/mitchellh/cli/ui_colored.go
  vendor/github.com/posener/complete/cmd/cmd.go
  vendor/github.com/posener/complete/cmd/install/fish.go
  vendor/github.com/posener/complete/cmd/install/install.go
  vendor/github.com/posener/complete/cmd/install/utils.go
  vendor/github.com/posener/complete/go.mod
  vendor/github.com/posener/complete/go.sum
  vendor/github.com/posener/complete/log.go
  vendor/github.com/posener/complete/match/file.go
  vendor/github.com/posener/complete/match/match.go
  vendor/github.com/posener/complete/match/prefix.go
  vendor/github.com/posener/complete/metalinter.json
  vendor/github.com/posener/complete/readme.md
  vendor/vendor.json
Labels: size/XL

#189 Backwards compatibility for AWS roles
  vault/migrate_aws_auth_backend_role.go
  vault/migrate_aws_auth_backend_role_test.go
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_tag_test.go
  vault/resource_aws_auth_backend_role_test.go
  website/docs/r/aws_auth_backend_role.html.md
Labels: size/XL

#156 Support v2 KV mount
  .travis.yml
  vault/data_source_generic_secret.go
  vault/data_source_generic_secret_test.go
  vault/kv_helpers.go
  vault/resource_generic_secret.go
  vault/resource_generic_secret_test.go
Labels: size/L

#193 Update vault api to version v0.11.1
  vendor/github.com/hashicorp/vault/api/auth_token.go
  vendor/github.com/hashicorp/vault/api/client.go
  vendor/github.com/hashicorp/vault/api/help.go
  vendor/github.com/hashicorp/vault/api/logical.go
  vendor/github.com/hashicorp/vault/api/secret.go
  vendor/github.com/hashicorp/vault/api/ssh.go
  vendor/github.com/hashicorp/vault/api/ssh_agent.go
  vendor/github.com/hashicorp/vault/api/sys_audit.go
  vendor/github.com/hashicorp/vault/api/sys_auth.go
  vendor/github.com/hashicorp/vault/api/sys_capabilities.go
  vendor/github.com/hashicorp/vault/api/sys_config_cors.go
  vendor/github.com/hashicorp/vault/api/sys_generate_root.go
  vendor/github.com/hashicorp/vault/api/sys_health.go
  vendor/github.com/hashicorp/vault/api/sys_init.go
  vendor/github.com/hashicorp/vault/api/sys_leader.go
  vendor/github.com/hashicorp/vault/api/sys_leases.go
  vendor/github.com/hashicorp/vault/api/sys_mounts.go
  vendor/github.com/hashicorp/vault/api/sys_plugins.go
  vendor/github.com/hashicorp/vault/api/sys_policy.go
  vendor/github.com/hashicorp/vault/api/sys_rekey.go
  vendor/github.com/hashicorp/vault/api/sys_rotate.go
  vendor/github.com/hashicorp/vault/api/sys_seal.go
  vendor/github.com/hashicorp/vault/api/sys_stepdown.go
  vendor/vendor.json
Labels: size/XL

#168 Allow for templated database backends
  vault/resource_database_secret_backend_connection.go
Labels: size/S

#195 Export LDAP Auth Backend accessor
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: size/S

#197 Update code examples to adhere to terraform fmt style.
  website/docs/d/kubernetes_auth_backend_config.md
  website/docs/r/aws_auth_backend_client.html.md
  website/docs/r/aws_auth_backend_login.html.md
  website/docs/r/cert_auth_backend_role.html.md
  website/docs/r/kubernetes_auth_backend_config.md
  website/docs/r/kubernetes_auth_backend_role.md
  website/docs/r/ldap_auth_backend_group.html.md
  website/docs/r/okta_auth_backend.html.md
  website/docs/r/okta_auth_backend_group.html.md
  website/docs/r/okta_auth_backend_user.html.md
Labels: size/S

#199 Remove duplicate navigation in docs for `vault_generic_secret`
  website/vault.erb
Labels: size/XS

#207 Improved example
  website/docs/d/generic_secret.html.md
Labels: size/XS

#211 Update database_secret_backend_role.md
  website/docs/r/database_secret_backend_role.md
Labels: size/XS

#216 [enh] implement rabbitmq secret backend and role
  vault/provider.go
  vault/provider_test.go
  vault/resource_rabbitmq_secret_backend.go
  vault/resource_rabbitmq_secret_backend_role.go
  vault/resource_rabbitmq_secret_backend_role_test.go
  vault/resource_rabbitmq_secret_backend_test.go
  website/docs/r/aws_secret_backend_role.html.md
  website/docs/r/rabbitmq_secret_backend.html.md
  website/docs/r/rabbitmq_secret_backend_role.html.md
  website/vault.erb
Labels: size/XL

#27 Add aws_auth_backend_roletag_blacklist resource.
  vault/provider.go
  vault/resource_aws_auth_backend_roletag_blacklist.go
  vault/resource_aws_auth_backend_roletag_blacklist_test.go
  website/docs/r/aws_auth_backend_roletag_blacklist.html.md
  website/vault.erb
Labels: enhancement, new-resource, size/XL

#209 Run vault and mysql in docker-compose for travis acceptance tests
  .test-env
  .travis.yml
  docker-compose.yaml
Labels: size/S

#212 [gcp] Add new `vault_gcp_secret_backend` resource for managing GCP
  vault/provider.go
  vault/resource_gcp_secret_backend.go
  vault/resource_gcp_secret_backend_test.go
  website/docs/r/gcp_secret_backend.html.md
Labels: size/XL

#222 Default booleans in AWS role resource
  vault/resource_aws_auth_backend_role.go
Labels: size/XS
