Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-03, with the labels that each got.

#336 RabbitMQ: Uses `vhosts` instead of `vhost`
  website/docs/r/rabbitmq_secret_backend_role.html.md
Labels: documentation, size/XS

#318 Fix some issues with updating fields for several resources
  vault/resource_gcp_auth_backend_role.go
  vault/resource_identity_group.go
  vault/resource_kubernetes_auth_backend_role.go
Labels: size/XS

#338 Add namespace resource
  vault/provider.go
  vault/resource_namespace.go
  vault/resource_namespace_test.go
  website/docs/r/namespace.html.md
Labels: documentation, size/L

#331 Add cidr blocks ssh otp
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/S

#316 Update `identity_entity` to use Sets for Policies
  vault/resource_identity_entity.go
  vault/resource_identity_entity_test.go
Labels: size/S

#362 Remove TestAccIdentityGroupExternal check
  vault/resource_identity_group_test.go
Labels: size/XS

#361 Fix typo in docs
  website/docs/r/cert_auth_backend_role.html.md
Labels: documentation, size/XS

#296 jwt_auth_backend_role: add groups_claim_delimiter_pattern support
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/README.md
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/backend.go
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_login.go
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_role.go
  vendor/vendor.json
  website/docs/r/jwt_auth_backend_role.html.md
Labels: dependencies, documentation, size/L

#314 Fix TTL on PKI certificate create to use string type and not int.
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
Labels: size/XS

#312 Add `vault_gcp_secret_roleset`
  vault/provider.go
  vault/provider_test.go
  vault/resource_gcp_secret_roleset.go
  vault/resource_gcp_secret_roleset_test.go
  website/docs/r/gcp_secret_backend.html.md
  website/docs/r/gcp_secret_roleset.html.md
Labels: documentation, size/XL

#340 Allow updating `data` on `vault_database_secret_backend_connection`
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/S

#330 Generic sercret data
  vault/resource_generic_secret.go
  vault/resource_generic_secret_test.go
  website/docs/r/generic_secret.html.md
Labels: documentation, size/S

#337 Add vault_token resource
  vault/provider.go
  vault/resource_token.go
  vault/resource_token_test.go
  website/docs/r/token.html.md
Labels: documentation, size/XL

#347 Update sidebar with missing documentation changes
  website/docs/r/github_auth_backend.html.md
  website/docs/r/github_team.html.md
  website/docs/r/github_user.html.md
  website/docs/r/identity_group_alias.html.md
  website/vault.erb
Labels: documentation, size/S

#350 Enable mount accessor export for vault_github_auth_backend
  vault/auth_mount.go
  vault/resource_github_auth_backend.go
  vault/resource_github_auth_backend_test.go
  website/docs/r/github_auth_backend.html.md
Labels: documentation, size/XS

#355 Add max_retries provider argument to set retries on 5xx api client errors.
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#357 [docs] Add 'gcp_auth_backend' resource to website docs
  website/vault.erb
Labels: documentation, size/XS

#374 Flexible generic secret
  vault/provider.go
  vault/resource_generic_endpoint.go
  vault/resource_generic_endpoint_test.go
  website/docs/r/generic_endpoint.html.md
  website/docs/r/generic_secret.html.md
  website/vault.erb
Labels: documentation, size/XL

#367 Add the use_token_groups field to ldap auth
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/S
