Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-04, with the labels that each got.

#375 Fix typo in sidebar for vault provider
  website/vault.erb
Labels: documentation, size/XS

#317 Update token_auth_backend_role
  docker-compose.yaml
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  vault/resource_token_auth_backend_role.go
  vault/resource_token_auth_backend_role_test.go
  website/docs/r/jwt_auth_backend_role.html.md
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/L

#344 removed conflicts between inline policy and policy_arns, updated tests
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
Labels: size/S

#345 Added support for jwt_supported_algs
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/S

#400 Switch to CircleCI
  .circleci/config.yml
  .travis.yml
Labels: size/S

#379 update documentation import for github auth backend
  website/docs/r/github_auth_backend.html.md
Labels: documentation, size/XS

#389 Tolerate missing policies in role.
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
Labels: size/XS

#373 Add param to configure uri_sans for CSRs
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
Labels: documentation, size/XS

#401 docs: Add missing gcp resources
  website/vault.erb
Labels: documentation, size/XS

#377 Fix approle_secret-id exists return
  vault/resource_approle_auth_backend_role_secret_id.go
Labels: size/XS

#387 Allow vault_ldap_auth resources to be imported
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_group.go
  vault/resource_ldap_auth_backend_group_test.go
  vault/resource_ldap_auth_backend_test.go
  vault/resource_ldap_auth_backend_user.go
  vault/resource_ldap_auth_backend_user_test.go
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/ldap_auth_backend_group.html.md
  website/docs/r/ldap_auth_backend_user.html.md
Labels: documentation, size/L

#391 Fixes trailing slash issue for namespaces
  vault/resource_namespace.go
  vault/resource_namespace_test.go
  website/docs/r/namespace.html.md
Labels: documentation, size/S

#392 Adds new validator for trailing slashes
  vault/resource_auth_backend.go
  vault/resource_jwt_auth_backend.go
  vault/validators.go
  vault/validators_test.go
Labels: size/M

#395 Handle "all policies deleted" corner case
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_test.go
Labels: size/S

#402 Refactors namespace to use validateFunc
  vault/resource_namespace.go
Labels: size/XS

#403 Switch to Go modules
  go.mod
  go.sum
  vendor/vendor.json
Labels: dependencies, size/XXL
