Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-05, with the labels that each got.

#386 implement renewal of pki certs with min_seconds_remaining argument
  go.mod
  go.sum
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
  website/docs/r/pki_secret_backend_cert.html.md
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: dependencies, documentation, size/XL

#396 Don't overwrite vault_namespace path with response value.
  vault/resource_namespace.go
  vault/resource_namespace_test.go
Labels: size/S

#398 Support OIDC auth backends
  vault/resource_auth_backend.go
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  vault/resource_jwt_auth_backend_test.go
  website/docs/r/jwt_auth_backend.html.md
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/XL

#399 Add pki config urls
  .gitignore
  vault/provider.go
  vault/resource_pki_secret_backend_config_urls.go
  vault/resource_pki_secret_backend_config_urls_test.go
  website/docs/r/pki_secret_backend_config_urls.html.md
  website/vault.erb
Labels: documentation, size/L

#404 updated `use_token_auth` to `use_token_groups`
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/XS

#421 [docs] Add missing token resource page link
  website/vault.erb
Labels: documentation, size/XS
