Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-12, with the labels that each got.

#625 Fix build
  vault/resource_token_test.go
Labels: size/XS

#618 Add missing link to `vault_database_secret_backend_static_role` docs
  website/vault.erb
Labels: documentation, size/XS

#605 Add allowed_user_key_lengths support to vault_ssh_secret_backend_role
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#610 correctly update name attribute of vault_identity_entity_alias resources
  vault/resource_identity_entity_alias.go
  vault/resource_identity_entity_alias_test.go
Labels: size/M

#626 Update openapi.json
  testdata/openapi.json
Labels: size/XS

#594 Add token name provider argument
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#616 Fix #613 - Add `seal_wrap` to resource "vault_mount"
  vault/resource_mount.go
  vault/resource_mount_test.go
  website/docs/r/mount.html.md
Labels: documentation, size/M

#601 Add new k8s auth backend params
  vault/data_source_kubernetes_auth_backend_config.go
  vault/data_source_kubernetes_auth_backend_config_test.go
  vault/data_source_kubernetes_auth_backend_role.go
  vault/data_source_kubernetes_auth_backend_role_test.go
  vault/resource_kubernetes_auth_backend_config.go
  vault/resource_kubernetes_auth_backend_config_test.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role_test.go
  website/docs/d/kubernetes_auth_backend_config.md
  website/docs/d/kubernetes_auth_backend_role.md
  website/docs/r/kubernetes_auth_backend_config.md
  website/docs/r/kubernetes_auth_backend_role.html.md
Labels: documentation, size/L

#606 Add auth_backend data source
  vault/data_source_auth_backend.go
  vault/data_source_auth_backend_test.go
  vault/provider.go
  website/docs/d/auth_backend.html.md
  website/vault.erb
Labels: documentation, size/L

#627 Prevent panic when Cassandra protocol_version is set
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/M

#635 Update GCP secrets credentials on change
  vault/resource_gcp_secret_backend.go
  vault/resource_gcp_secret_backend_test.go
Labels: size/XS

#629 document required token policies for the vault_token resource
  website/docs/r/token.html.md
Labels: documentation, size/XS

#634 aws_secret_backend: credentials are optional
  vault/resource_aws_secret_backend.go
  vault/resource_aws_secret_backend_test.go
  website/docs/r/aws_secret_backend.html.md
Labels: documentation, size/S

#637 identity_*_policies: fix policies updates not removing old policies
  vault/resource_identity_entity_policies.go
  vault/resource_identity_entity_policies_test.go
  vault/resource_identity_group_policies.go
  vault/resource_identity_group_policies_test.go
Labels: documentation, size/L
