Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-06, with the labels that each got.

#431 Vendor the go-rootcerts package
  vendor/github.com/hashicorp/go-rootcerts/go.mod
  vendor/github.com/hashicorp/go-rootcerts/go.sum
  vendor/modules.txt
Labels: dependencies, size/XS

#407 aws_secret_backend_role: support role_arns argument
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/M

#415 Implement tests alongside an improved fix for #368
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#420 Implement "accessor" attribute on vault_okta_auth_backend
  vault/resource_okta_auth_backend.go
  vault/resource_okta_auth_backend_test.go
  website/docs/r/okta_auth_backend.html.md
Labels: documentation, size/XS

#426 Remove default TTLs for vault_gcp_secret_backend
  vault/resource_gcp_secret_backend.go
  vault/resource_gcp_secret_backend_test.go
  website/docs/r/gcp_secret_backend.html.md
Labels: documentation, size/XS

#433 Read Namespace Information from Token
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#435 Run acceptance tests through CI
  .circleci/config.yml
Labels: size/S

#434 Allowing for the token to be read from the environment
  vault/provider.go
Labels: size/XS

#441 Add namespace docs to sidebar
  website/vault.erb
Labels: documentation, size/XS

#411 Fix GCP auth backend role
  vault/resource_gcp_auth_backend_role.go
  vault/resource_gcp_auth_backend_role_test.go
Labels: size/XS

#453 Add sidebar menu link to vault_policy_document document
  website/vault.erb
Labels: documentation, size/XS
