Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-07, with the labels that each got.

#445 Minor spelling fixes
  website/docs/r/azure_auth_backend_role.html.md
  website/docs/r/gcp_auth_backend.html.md
  website/docs/r/gcp_secret_backend.html.md
Labels: documentation, size/XS

#439 Update AWS Auth Backend Role resources to take sets instead of lists
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_tag.go
  vault/resource_aws_auth_backend_role_test.go
Labels: size/M

#455 Add list type for bound claims of vault_jwt_auth_backend_role
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
Labels: size/S

#457 Fix code example
  website/docs/d/policy_document.md
Labels: documentation, size/XS

#444 Add STS TTLs to `vault_aws_secret_backend_role`
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/M

#456 Always set attribute 'data' if read is disabled
  vault/resource_generic_secret.go
Labels: size/S

#461 aws_auth_backend_client supports nested paths
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
Labels: size/S
