Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-10, with the labels that each got.

#548 Add support for configuring the Transit cache
  vault/provider.go
  vault/resource_transit_cache_config.go
  vault/resource_transit_cache_config_test.go
  website/docs/r/transit_secret_backend_cache_config.html.md
Labels: documentation, size/L

#530 Add root_rotation_statements to vault_database_secret_backend_connection
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/S

#552 Add support for alternative auth methods using a method-agnostic implementation
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#556 Support token_type and allowed_response_headers in github_auth_backend and jwt_auth_backend
  vault/auth_mount.go
  vault/resource_github_auth_backend_test.go
  vault/structures.go
  vault/structures_test.go
  website/docs/r/github_auth_backend.html.md
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/M

#534 docs: vault_token_auth_backend_role does not support token_policies attribute
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/XS

#566 Add new JWT Auth Role Fields introduced with Vault 1.2
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/M

#571 Wait longer for AWS creds to propagate
  vault/data_source_aws_access_credentials.go
Labels: size/M

#562 Correct bad markdown
  website/docs/index.html.markdown
Labels: documentation, size/XS

#576 Document data attribute
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/XS

#579 Add whitelines to address hanging "```"
  website/docs/index.html.markdown
Labels: documentation, size/XS

#565 Add information about Vault 1.2 for `token_*` fields
  vault/data_source_kubernetes_auth_backend_role.go
  vault/resource_approle_auth_backend_role.go
  vault/resource_aws_auth_backend_role.go
  vault/resource_azure_auth_backend_role.go
  vault/resource_cert_auth_backend_role.go
  vault/resource_gcp_auth_backend_role.go
  vault/resource_github_auth_backend.go
  vault/resource_jwt_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_token_auth_backend_role.go
  website/docs/d/kubernetes_auth_backend_role.md
  website/docs/r/approle_auth_backend_role.html.md
  website/docs/r/aws_auth_backend_role.html.md
  website/docs/r/azure_auth_backend_role.html.md
  website/docs/r/cert_auth_backend_role.html.md
  website/docs/r/gcp_auth_backend_role.html.md
  website/docs/r/github_auth_backend.html.md
  website/docs/r/jwt_auth_backend_role.html.md
  website/docs/r/kubernetes_auth_backend_role.html.md
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/L

#582 Adding sidebar link to crl_config
  website/vault.erb
Labels: documentation, size/XS

#585 Fix missing quote that breaks documentation rendering.
  website/docs/r/aws_auth_backend_roletag_blacklist.html.md
Labels: documentation, size/XS

#586 Add missing docs for `identity_group_policies`
  website/docs/r/identity_group.html.md
  website/docs/r/identity_group_policies.html.md
  website/vault.erb
Labels: documentation, size/M

#588 fix code blocks formatting and vault_azure_secret_* links titles
  website/vault.erb
Labels: documentation, size/XS

#577 Added vault_database_secret_backend_static_role resource
  go.sum
  vault/provider.go
  vault/resource_database_secret_backend_static_role.go
  vault/resource_database_secret_backend_static_role_test.go
  website/docs/r/database_secret_backend_static_role.md
Labels: documentation, size/XL
