Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-11, with the labels that each got.

#573 Fix panic when trying to write an entity alias that already exists
  vault/resource_identity_entity_alias.go
  vault/resource_identity_entity_alias_test.go
Labels: size/S

#592 Add missing quote to vault consul docs
  website/docs/r/consul_secret_backend_role.html.md
Labels: documentation, size/XS

#581 Add missing attributes and allow importing on consul_secret_backend_role
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  website/docs/r/consul_secret_backend_role.html.md
Labels: documentation, size/XL

#597 Fix typo in vault_github_team doc
  website/docs/r/github_team.html.md
Labels: documentation, size/XS

#570 Change vault_namespace ID to path
  vault/resource_namespace.go
Labels: size/XS

#599 Undo Deprecation of `vault_identity_oidc_key_allowed_client_id`
  vault/provider.go
  vault/resource_identity_oidc_key_allowed_client_id.go
Labels: size/XS

#608 website: Move guide to be ingressed by the Terraform Registry
  website/docs/guides/version_2_upgrade.html.markdown
  website/vault.erb
Labels: documentation, size/XS

#559 Fix panic when importing from cassandra db
  vault/resource_database_secret_backend_connection.go
Labels: size/XS
