Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-08, with the labels that each got.

#458 Update docs for pki_secret_backend_config_urls
  website/docs/r/pki_secret_backend_config_urls.html.md
Labels: documentation, size/XS

#479 document auto_renew attribute
  website/docs/r/pki_secret_backend_cert.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: documentation, size/XS

#443 Adds MFA Duo configuration
  vault/provider.go
  vault/resource_mfa_duo.go
  vault/resource_mfa_duo_test.go
  website/docs/r/mfa_duo.html.md
  website/vault.erb
Labels: documentation, size/L

#465 Changes in vault_ldap_auth_backend_group groupname should trigger 'de…
  vault/resource_ldap_auth_backend_group.go
Labels: size/XS

#476 Minor enhancements to `vault_gcp_secret_roleset`
  vault/resource_gcp_secret_roleset.go
  vault/resource_gcp_secret_roleset_test.go
  website/docs/r/gcp_secret_roleset.html.md
Labels: documentation, size/M

#482 Update OpenAPI doc
  testdata/openapi.json
Labels: size/XS

#462 Exposing local flag on vault_mount resource
  vault/resource_mount.go
  vault/resource_mount_test.go
  website/docs/r/mount.html.md
Labels: documentation, size/M

#490 Begin deprecating duplicate resource
  vault/provider.go
  vault/resource_pki_secret_backend.go
Labels: size/XS

#481 Add Azure Secret Backend resource
  vault/provider.go
  vault/resource_azure_secret_backend.go
  vault/resource_azure_secret_backend_test.go
  website/docs/r/azure_secret_backend.html.md
Labels: documentation, size/XL

#492 Use Mutex to lock Identity Group Updates
  vault/provider.go
  vault/resource_identity_group.go
  vault/resource_identity_group_policies.go
Labels: size/XS

#477 Add Resources for Transit Secrets Backend
  vault/provider.go
  vault/resource_transit_secret_backend_key.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/XL

#488 Add resources for Vault Identity Tokens
  go.sum
  util/util.go
  util/util_test.go
  vault/provider.go
  vault/resource_identity_oidc.go
  vault/resource_identity_oidc_key.go
  vault/resource_identity_oidc_key_allowed_client_id.go
  vault/resource_identity_oidc_key_allowed_client_id_test.go
  vault/resource_identity_oidc_key_test.go
  vault/resource_identity_oidc_role.go
  vault/resource_identity_oidc_role_test.go
  vault/resource_identity_oidc_test.go
  website/docs/r/identity_oidc.html.md
  website/docs/r/identity_oidc_key.html.md
  website/docs/r/identity_oidc_key_allowed_client_id.html.md
  website/docs/r/identity_oidc_role.html.md
Labels: documentation, size/XXL

#494 Add data sources for identity entity and group
  vault/data_identity_entity.go
  vault/data_identity_entity_test.go
  vault/data_identity_group.go
  vault/data_identity_group_test.go
  vault/provider.go
  website/docs/d/identity_entity.html.md
  website/docs/d/identity_group.html.md
Labels: documentation, size/XXL

#493 Add vault azure secret backend role
  vault/provider.go
  vault/resource_azure_secret_backend_role.go
  vault/resource_azure_secret_backend_role_test.go
  website/docs/r/azure_secret_backend_role.html.md
Labels: documentation, size/XL

#495 Fix Non-Exclusive Behaviour of `identity_group_policies`
  vault/resource_identity_group.go
  vault/resource_identity_group_policies.go
  vault/resource_identity_group_policies_test.go
Labels: size/L

#423 tokenRead will renew resource token instead of access token
  vault/resource_token.go
  vault/resource_token_test.go
Labels: size/XS

#509 Don't require the GCP auth credentials field
  vault/resource_gcp_auth_backend.go
  website/docs/r/gcp_auth_backend.html.md
Labels: documentation, size/XS

#483 add new JWKS options for the JWT auth mount
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/L

#518 Add support for response-wrapping AppRole secret IDs
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/resource_approle_auth_backend_role_secret_id_test.go
  website/docs/r/approle_auth_backend_role_secret_id.html.md
Labels: documentation, size/L

#515 Support mount type "kv-v2"
  vault/import_mount_test.go
  vault/resource_mount.go
  vault/resource_mount_test.go
Labels: size/M

#513 website: link to transit_secret_backend_key
  website/docs/r/transit_secret_backend_key.html.md
  website/vault.erb
Labels: documentation, size/XS

#500 Fix missing sidebar links and broken links
  website/docs/d/identity_entity.html.md
  website/docs/d/identity_group.html.md
  website/docs/r/identity_oidc_role.html.md
  website/vault.erb
Labels: documentation, size/S
