Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-01, with the labels that each got.

#262 Support for namespaces
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#279 Fix token_auth_backend_role role_name updates not working
  vault/resource_token_auth_backend_role.go
  vault/resource_token_auth_backend_role_test.go
Labels: size/S

#284 Fix resource name in docs menu
  website/docs/r/aws_secret_backend_role.html.md
  website/vault.erb
Labels: documentation, size/XS

#280 Fix doc to add required params of vault_cert_auth_backend_role
  website/docs/r/cert_auth_backend_role.html.md
Labels: documentation, size/XS

#264 Added support for EGP and RGP (sentinel)
  vault/provider.go
  vault/resource_egp_policy.go
  vault/resource_egp_policy_test.go
  vault/resource_rgp_policy.go
  vault/resource_rgp_policy_test.go
  vault/sentinel.go
  website/docs/r/egp_policy.html.md
  website/docs/r/rgp_policy.html.md
  website/vault.erb
Labels: documentation, size/XL

#158 Add PKI secret backend
  vault/provider.go
  vault/resource_pki_secret_backend.go
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_config_ca.go
  vault/resource_pki_secret_backend_config_ca_test.go
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_intermediate_set_signed.go
  vault/resource_pki_secret_backend_intermediate_set_signed_test.go
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
  vault/resource_pki_secret_backend_test.go
  website/docs/r/pki_secret_backend.html.md
  website/docs/r/pki_secret_backend_cert.html.md
  website/docs/r/pki_secret_backend_config_ca.html.md
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
  website/docs/r/pki_secret_backend_intermediate_set_signed.html.md
  website/docs/r/pki_secret_backend_role.html.md
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
  website/vault.erb
Labels: documentation, size/XXL

#243 Fix wrong response data from gcp_auth_backend_role read request
  vault/resource_gcp_auth_backend_role.go
Labels: size/XS

#288 Fix for namespaces (#262)
  vault/provider.go
Labels: size/XS

#255 Implement Github Auth Backend resources
  .gitignore
  util/util.go
  vault/auth_mount.go
  vault/github.go
  vault/provider.go
  vault/resource_github_auth_backend.go
  vault/resource_github_auth_backend_test.go
  vault/resource_github_team.go
  vault/resource_github_team_test.go
  vault/resource_github_user.go
  vault/resource_github_user_test.go
  vault/structures.go
  vault/structures_test.go
  vault/validators.go
  vendor/github.com/gosimple/slug/LICENSE
  vendor/github.com/gosimple/slug/README.md
  vendor/github.com/gosimple/slug/doc.go
  vendor/github.com/gosimple/slug/languages_substitution.go
  vendor/github.com/gosimple/slug/slug.go
  vendor/github.com/rainycape/unidecode/LICENSE
  vendor/github.com/rainycape/unidecode/README.md
  vendor/github.com/rainycape/unidecode/decode.go
  vendor/github.com/rainycape/unidecode/make_table.go
  vendor/github.com/rainycape/unidecode/table.go
  vendor/github.com/rainycape/unidecode/table.txt
  vendor/github.com/rainycape/unidecode/unidecode.go
  vendor/vendor.json
  website/docs/r/github_auth_backend.html.md
  website/docs/r/github_team.html.md
  website/docs/r/github_user.html.md
Labels: dependencies, documentation, size/XXL

#287 Add identity entity
  website/docs/r/identity_entity.html.md
  website/docs/r/identity_entity_alias.html.md
  website/vault.erb
Labels: documentation, size/M

#272 Support JWT auth backend
  vault/provider.go
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  website/docs/r/jwt_auth_backend.html.md
  website/vault.erb
Labels: documentation, size/XL

#285 Add vault_ssh_secret_backend_role resource
  vault/provider.go
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
  website/vault.erb
Labels: documentation, size/XL

#291 Fix documentation
  website/docs/r/approle_auth_backend_login.html.md
  website/docs/r/approle_auth_backend_role.html.md
  website/docs/r/approle_auth_backend_role_secret_id.html.md
  website/docs/r/gcp_auth_backend.html.md
  website/docs/r/identity_entity.html.md
  website/docs/r/identity_entity_alias.html.md
  website/docs/r/jwt_auth_backend_role.html.md
  website/docs/r/kubernetes_auth_backend_config.md
  website/docs/r/kubernetes_auth_backend_role.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
  website/vault.erb
Labels: documentation, size/S

#270 Fix issue where boolean parameters are not being set when value is false
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_test.go
Labels: size/S
