Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-09, with the labels that each got.

#524 Update doc for PKI secret backend
  website/docs/r/pki_secret_backend_root_cert.html.md
Labels: documentation, size/XS

#512 Fix PKI Config URLs Update
  vault/resource_pki_secret_backend_config_urls.go
Labels: size/XS

#514 Add import for okta backend group resource
  vault/resource_okta_auth_backend_group.go
  vault/resource_okta_auth_backend_group_test.go
  website/docs/r/okta_auth_backend_group.html.md
Labels: documentation, size/M

#517 Support GCP auth backend role import
  vault/resource_gcp_auth_backend_role.go
  vault/resource_gcp_auth_backend_role_test.go
  website/docs/r/gcp_auth_backend.html.md
  website/docs/r/gcp_auth_backend_role.html.md
Labels: documentation, size/M

#528 Fix build
  go.mod
  go.sum
Labels: size/XS

#529 Update coverage report
  testdata/openapi.json
Labels: size/XS

#543 Move new token fields from Github teams/users into config
  vault/resource_github_auth_backend.go
  vault/resource_github_team.go
  vault/resource_github_team_test.go
  vault/resource_github_user.go
  vault/resource_github_user_test.go
  website/docs/r/github_auth_backend.html.md
  website/docs/r/github_team.html.md
  website/docs/r/github_user.html.md
Labels: documentation, size/XL

#553 Add support for Vault 1.2+ token fields to LDAP auth
  vault/resource_ldap_auth_backend.go
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/L

#536 Allow identity group alias name to be updated
  vault/resource_identity_group_alias.go
  vault/resource_identity_group_alias_test.go
Labels: size/S

#539 Improve AWS secret backend client configuration
  vault/resource_aws_secret_backend.go
  website/docs/r/aws_secret_backend.html.md
Labels: documentation, size/S

#547 Fix some typos in resource_okta_auth_backend_group errors
  vault/resource_okta_auth_backend_group.go
Labels: size/XS

#554 Update the OpenAPI doc used for the coverage report
  testdata/openapi.json
Labels: size/XS

#506 Feature/pki crl config
  vault/provider.go
  vault/resource_pki_secret_backend_crl_config.go
  vault/resource_pki_secret_backend_crl_config_test.go
  website/docs/r/pki_secret_backend_crl_config.html.md
Labels: documentation, size/L

#540 Only update aws_auth_backend_client aws creds if they change
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
Labels: size/M
