Repository hashicorp/terraform-provider-vault, pull requests merged in 2019-02, with the labels that each got.

#292 Update to Vault 1.0
  docker-compose.yaml
  vault/resource_gcp_auth_backend_role.go
  vault/resource_gcp_auth_backend_role_test.go
  website/docs/r/gcp_auth_backend_role.html.md
Labels: documentation, size/S

#306 Improve styling of CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: size/XS

#302 Set `token_reviewer_jwt` in `kubernetes_auth_backend_config` as sensitive
  vault/resource_kubernetes_auth_backend_config.go
Labels: size/XS

#309 backend -> path in Consul secret backend resource
  website/docs/r/consul_secret_backend.html.md
Labels: documentation, size/XS

#283 Add vault_policy_document data source
  vault/data_source_policy_document.go
  vault/data_source_policy_document_test.go
  vault/provider.go
  website/docs/d/policy_document.md
Labels: documentation, size/XL

#303 ssh role add missing parameters
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#310 Problem: Nil ca chain in response causes segfault
  vault/resource_pki_secret_backend_cert.go
Labels: size/XS

#308 Add fields to `vault_gcp_auth_backend_role`
  vault/resource_gcp_auth_backend_role.go
  vault/resource_gcp_auth_backend_role_test.go
  website/docs/r/gcp_auth_backend_role.html.md
Labels: documentation, size/L

#305 Fix `kubernetes_auth_backend_role` issues
  vault/data_source_kubernetes_auth_backend_role.go
  vault/data_source_kubernetes_auth_backend_role_test.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role_test.go
  website/docs/d/kubernetes_auth_backend_role.md
  website/docs/r/kubernetes_auth_backend_role.html.md
Labels: documentation, size/XL

#311 Add docs for `identity_group*` resources
  website/docs/r/identity_group.html.md
  website/docs/r/identity_group_alias.html.md
Labels: documentation, size/M

#301 Fix some issues with `vault_identity_group`
  vault/resource_identity_group.go
  vault/resource_identity_group_alias.go
  vault/resource_identity_group_test.go
Labels: size/M

#323 Fix tests for AWS secret engine roles
  vault/data_source_aws_access_credentials_test.go
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/L

#327 Fix tests that pull EC2 instance metadata
  vault/resource_aws_auth_backend_login_test.go
Labels: size/XS

#328 Skip unsuitable tests
  vault/resource_aws_auth_backend_login_test.go
Labels: size/XS

#319 tests: Special case empty string in TestCheckResourceAttrJSON
  util/util.go
Labels: size/XS
