Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-11, with the labels that each got.

#803 jwt_auth_backend: fix oidc_client_secret storage
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
Labels: size/XS

#896 docs: update 'time to leave' to 'time to live'
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_sign.go
Labels: size/XS

#893 add/update docs for namespaces
  website/docs/index.html.markdown
Labels: documentation, size/L

#878 Add optional TTL to data.vault_aws_access_credentials
  vault/data_source_aws_access_credentials.go
  vault/data_source_aws_access_credentials_test.go
  website/docs/d/aws_access_credentials.html.md
Labels: documentation, size/M

#898 Update jira sync github action
  .github/workflows/jira.yaml
Labels: ecosystem, size/M

#902 Add Active Directory secret engine support
  CHANGELOG.md
  go.mod
  go.sum
  testdata/openapi.json
  testdata/user.ldif
  util/util.go
  vault/data_source_ad_credentials.go
  vault/data_source_ad_credentials_test.go
  vault/provider.go
  vault/provider_test.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_backend_test.go
  vault/resource_ad_secret_library.go
  vault/resource_ad_secret_library_test.go
  vault/resource_ad_secret_roles.go
  vault/resource_ad_secret_roles_test.go
  website/docs/d/ad_access_credentials.html.md
  website/docs/r/ad_secret_backend.html.md
  website/docs/r/ad_secret_backend_library.html.md
  website/docs/r/ad_secret_backend_role.html.md
  website/docs/r/transform_alphabet.html.md
  website/docs/r/transform_role.html.md
  website/docs/r/transform_template.html.md
  website/docs/r/transform_transformation.html.md
  website/vault.erb
Labels: documentation, size/XXL

#916 Disable failing test TestAccIdentityGroupMemberEntityIdsExclusive
  vault/resource_identity_group_member_entity_ids_test.go
Labels: bug, size/XS

#915 Add local to audit resource
  vault/resource_audit.go
  vault/resource_audit_test.go
  website/docs/r/audit.html.md
Labels: documentation, enhancement, size/S

#899 Fix Terraform crash when creating an entity that already exists
  vault/resource_identity_entity.go
  website/docs/r/identity_entity.html.md
Labels: documentation, size/XS

#919 update go mod to point to hashicorp/terraform-provider-vault
  cmd/coverage/main.go
  cmd/generate/main.go
  codegen/generate.go
  codegen/templates/datasource.go.tpl
  codegen/templates/resource.go.tpl
  generated/datasources/transform/decode/role_name.go
  generated/datasources/transform/decode/role_name_test.go
  generated/datasources/transform/encode/role_name.go
  generated/datasources/transform/encode/role_name_test.go
  generated/resources/transform/alphabet/name.go
  generated/resources/transform/alphabet/name_test.go
  generated/resources/transform/role/name.go
  generated/resources/transform/role/name_test.go
  generated/resources/transform/template/name.go
  generated/resources/transform/template/name_test.go
  generated/resources/transform/transformation/name.go
  generated/resources/transform/transformation/name_test.go
  generated/terraform_registry.go
  go.mod
  main.go
  vault/data_source_ad_credentials_test.go
  vault/okta.go
  vault/provider_test.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_backend_test.go
  vault/resource_ad_secret_library.go
  vault/resource_ad_secret_library_test.go
  vault/resource_ad_secret_roles.go
  vault/resource_ad_secret_roles_test.go
  vault/resource_approle_auth_backend_login.go
  vault/resource_approle_auth_backend_role.go
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/resource_approle_auth_backend_role_test.go
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_identity_entity.go
  vault/resource_identity_entity_policies.go
  vault/resource_identity_entity_policies_test.go
  vault/resource_identity_group.go
  vault/resource_identity_group_member_entity_ids.go
  vault/resource_identity_group_member_entity_ids_test.go
  vault/resource_identity_group_policies.go
  vault/resource_identity_group_policies_test.go
  vault/resource_identity_oidc_key_allowed_client_id.go
  vault/resource_identity_oidc_key_allowed_client_id_test.go
  vault/resource_jwt_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_ldap_auth_backend_group_test.go
  vault/resource_ldap_auth_backend_user.go
  vault/resource_ldap_auth_backend_user_test.go
  vault/resource_okta_auth_backend.go
  vault/resource_okta_auth_backend_group.go
  vault/resource_okta_auth_backend_test.go
  vault/resource_okta_auth_backend_user.go
  vault/structures.go
  website/docs/guides/version_2_upgrade.html.markdown
Labels: size/L

#920 update references of terraform-providers org
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  scripts/changelog-links.sh
Labels: size/XS

#921 Adds doc instructions on how to import
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/XS
