Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-10, with the labels that each got.

#872 Add vault_transit_encrypt and vault_transit_decrypt
  vault/data_source_transit_decrypt.go
  vault/data_source_transit_decrypt_test.go
  vault/data_source_transit_encrypt.go
  vault/data_source_transit_encrypt_test.go
  vault/provider.go
  website/docs/d/transit_decrypt.md
  website/docs/d/transit_encrypt.md
Labels: documentation, size/XL

#871 Generated docs path update
  codegen/endpoint_registry.go
  codegen/generate.go
  codegen/generate_test.go
  website/docs/d/transform_decode.html.md
  website/docs/d/transform_encode.html.md
  website/docs/r/transform_alphabet.html.md
  website/docs/r/transform_role.html.md
  website/docs/r/transform_template.html.md
  website/docs/r/transform_transformation.html.md
Labels: documentation, size/M

#870 [k8s auth backend confiugration] Introduce disable_iss_validation and disable_local_ca_jwt params
  vault/data_source_kubernetes_auth_backend_config.go
  vault/data_source_kubernetes_auth_backend_config_test.go
  vault/resource_kubernetes_auth_backend_config.go
  vault/resource_kubernetes_auth_backend_config_test.go
  website/docs/r/kubernetes_auth_backend_config.md
Labels: documentation, size/M

#875 vault_ssh_secret_backend_role: add allowed_users_template argument
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#809 vault_ssh_secret_backend_role: add algorithm_signer argument
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#861 Feature request for issue #858
  vault/resource_gcp_auth_backend.go
  website/docs/r/gcp_auth_backend.html.md
Labels: documentation, size/XS

#885 Fix vault_transit_secret_cache_config documentation
  website/docs/r/transit_secret_backend_cache_config.html.md
Labels: documentation, size/XS
