Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-01, with the labels that each got.

#639 Fix example to be compatible with 0.12
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/XS

#649 Change JWT bound_audiences to be optional
  vault/resource_jwt_auth_backend_role.go
Labels: size/XS

#654 docs: add example for using aliases for multiple Vault namespaces
  website/docs/index.html.markdown
Labels: documentation, size/XS

#646 fix(resource_transit_secret_backend_key): add more officially supported key types
  vault/resource_transit_secret_backend_key.go
Labels: size/XS

#647 Fix name of argument in documentation
  website/docs/r/aws_auth_backend_login.html.md
Labels: documentation, size/XS

#661 Add support to select AWS ARN from role with multiple configured
  README.md
  vault/data_source_aws_access_credentials.go
  vault/data_source_aws_access_credentials_test.go
  website/docs/d/aws_access_credentials.html.md
Labels: documentation, size/L

#656 Sort vault_policy_document allowed/denied parameters by key name
  vault/data_source_policy_document.go
  vault/data_source_policy_document_test.go
Labels: size/S

#657 token_policy argument
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/XS

#655 ldap_auth_backend_user: fix diff when groups is empty
  vault/resource_ldap_auth_backend_user.go
  vault/resource_ldap_auth_backend_user_test.go
Labels: size/M
