Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-03, with the labels that each got.

#692 Fix typo
  website/docs/index.html.markdown
Labels: documentation, size/XS

#695 Missing double quote.
  website/docs/r/azure_auth_backend_config.html.md
Labels: documentation, size/XS

#690 vault_cert_auth_backend_role: delete on delete
  vault/resource_cert_auth_backend_role.go
Labels: size/XS

#674 Fix `use_token_groups` change in `vault_ldap_auth_backend`
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
Labels: size/XS

#697 Update auth_backend resource documentation
  website/docs/r/auth_backend.html.md
Labels: documentation, size/S

#673 Add `vault_alicloud_auth_backend_role` resource
  vault/provider.go
  vault/resource_alicloud_auth_backend_role.go
  vault/resource_alicloud_auth_backend_role_test.go
  website/docs/r/alicloud_auth_backend_role.md
  website/docs/r/gcp_auth_backend_role.html.md
  website/vault.erb
Labels: documentation, size/XL

#687 fix(okta_auth_backend_group): allow '/' in group_name
  vault/resource_okta_auth_backend.go
  vault/resource_okta_auth_backend_group.go
  vault/resource_okta_auth_backend_group_test.go
  vault/resource_okta_auth_backend_test.go
  vault/resource_okta_auth_backend_user.go
  vault/resource_okta_auth_backend_user_test.go
Labels: size/L

#698 Support not_before_duration property in pki_secret_backend_role
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/XS

#699 Update auth_backend doc to reflect argument deprecation and tune block
  website/docs/r/auth_backend.html.md
  website/docs/r/github_auth_backend.html.md
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/XS

#705 Add import section to kubernetes_auth_backend_role documentation
  website/docs/r/kubernetes_auth_backend_role.html.md
Labels: documentation, size/XS

#708 Fix vault_policy example Documentation
  website/docs/r/policy.html.md
Labels: documentation, size/XS

#713 Add Azure data source that can validate new creds
  vault/data_source_azure_access_credentials.go
  vault/data_source_azure_access_credentials_test.go
  vault/provider.go
  vault/provider_test.go
  website/docs/d/azure_access_credentials.html.md
  website/vault.erb
Labels: documentation, secret/azure, size/XL

#651 Set VAULT_ADDR in process env when using token helper
  CHANGELOG.md
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/XL

#710 aws_secret_backend: allow role_arns with policy_arns
  vault/resource_aws_secret_backend_role.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/XS
