Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-05, with the labels that each got.

#738 Add directory structure
  codegen/generate.go
  codegen/generate_test.go
  codegen/templates.go
Labels: size/L

#744 vault_approle_auth_backend_role: Fix perpetual diff when upgrading from `policies` to `token_policies`
  vault/resource_approle_auth_backend_role.go
  vault/resource_approle_auth_backend_role_test.go
Labels: bug, size/M

#745 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#720 Fix approle_auth_backend docs links
  website/docs/r/approle_auth_backend_login.html.md
  website/docs/r/approle_auth_backend_role.html.md
  website/docs/r/approle_auth_backend_role_secret_id.html.md
Labels: documentation, size/XS

#721 Fix broken link to Vault's GitHub auth backend
  website/docs/r/github_auth_backend.html.md
  website/docs/r/github_team.html.md
  website/docs/r/github_user.html.md
Labels: documentation, size/XS

#726 update broken links to api-docs
  website/docs/d/kubernetes_auth_backend_config.md
  website/docs/d/kubernetes_auth_backend_role.md
  website/docs/index.html.markdown
  website/docs/r/alicloud_auth_backend_role.md
  website/docs/r/aws_auth_backend_cert.html.md
  website/docs/r/aws_auth_backend_client.html.md
  website/docs/r/aws_auth_backend_identity_whitelist.html.md
  website/docs/r/azure_auth_backend_config.html.md
  website/docs/r/cert_auth_backend_role.html.md
  website/docs/r/database_secret_backend_connection.md
  website/docs/r/gcp_auth_backend.html.md
  website/docs/r/gcp_auth_backend_role.html.md
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/ldap_auth_backend_group.html.md
  website/docs/r/ldap_auth_backend_user.html.md
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/S

#731 Fix typo in path validation
  vault/resource_gcp_auth_backend_role.go
Labels: size/XS

#741 Document vault_azure_secret_backend mount path parameter
  website/docs/r/azure_secret_backend.html.md
Labels: documentation, size/XS

#739 fix(secret/database): do not send password on updates, unless it changed
  .circleci/config.yml
  docker-compose.yaml
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/L

#740 token: avoid panic when expire_time is nil
  vault/resource_token.go
Labels: size/XS

#746 1. Add code generation for a resource
  GNUmakefile
  cmd/generate/main.go
  codegen/endpoint_registry.go
  codegen/generate.go
  codegen/generate_test.go
  codegen/templates.go
  codegen/templates/resource.go.tpl
  codegen/templates_test.go
  generated/resources/transform/role/name.go
  generated/resources/transform/role/name_test.go
  generated/terraform_registry.go
  go.mod
  main.go
  util/util.go
  util/util_test.go
  vault/provider.go
  vault/resource_mount.go
Labels: size/XXL

#757 7. Add a resource for /transform/template/{name}
  codegen/endpoint_registry.go
  generated/datasources/transform/decode/role_name_test.go
  generated/datasources/transform/encode/role_name_test.go
  generated/registry.go
  generated/resources/transform/alphabet/name_test.go
  generated/resources/transform/template/name.go
  generated/resources/transform/template/name_test.go
  generated/resources/transform/transformation/name_test.go
  website/docs/generated/resources/transform/template/name.md
Labels: documentation, size/XL

#750 3. Add a generated data source
  GNUmakefile
  codegen/README.md
  codegen/endpoint_registry.go
  codegen/generate.go
  codegen/templates.go
  codegen/templates/datasource.go.tpl
  codegen/templates/doc.go.tpl
  codegen/templates/resource.go.tpl
  codegen/templates_test.go
  generated/datasources/transform/decode/role_name.go
  generated/datasources/transform/decode/role_name_test.go
  generated/datasources/transform/encode/role_name.go
  generated/datasources/transform/encode/role_name_test.go
  generated/registry.go
  generated/resources/transform/alphabet/name.go
  generated/resources/transform/alphabet/name_test.go
  generated/resources/transform/template/name.go
  generated/resources/transform/template/name_test.go
  generated/resources/transform/transformation/name_test.go
  main.go
  website/docs/generated/datasources/transform/decode/role_name.md
  website/docs/generated/datasources/transform/encode/role_name.md
  website/docs/generated/resources/transform/alphabet/name.md
  website/docs/generated/resources/transform/role/name.md
  website/docs/generated/resources/transform/template/name.md
  website/docs/generated/resources/transform/transformation/name.md
  website/vault.erb
Labels: documentation, size/XXL

#763 Fix crash in vault_jwt_auth_backend_role when bound_audiences is nil
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/XS

#730 Allow setting HTTP headers
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#761 fix: using the right serial_number response key
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
Labels: size/XS

#766 Fix removal of policies, member_group_ids, and member_entity_ids from the vault_identity_group resource.
  vault/resource_identity_group.go
  vault/resource_identity_group_test.go
  website/docs/r/identity_group.html.md
Labels: documentation, size/M

#780 Add resource that supports importing jwt config
  codegen/endpoint_registry.go
  codegen/templates/resource.go.tpl
  generated/resources/auth/jwt/config.go
  generated/resources/auth/jwt/config_test.go
  generated/resources/transform/alphabet/name.go
  generated/resources/transform/role/name.go
  generated/resources/transform/template/name.go
  generated/resources/transform/transformation/name.go
  generated/terraform_registry.go
  util/util.go
  util/util_test.go
  vault/provider.go
  vault/resource_auth_backend.go
  website/docs/generated/resources/auth/jwt/config.md
  website/vault.erb
Labels: documentation, size/XL
