Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-08, with the labels that each got.

#841 Add region passing for non commercial regions
  vault/data_source_aws_access_credentials.go
  vault/data_source_aws_access_credentials_test.go
  vault/provider_test.go
Labels: size/S

#826 Add `iam_groups` to `vault_aws_secret_backend_role`
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/M

#844 data.vault_generic_secret: make data and data_json sensitive
  vault/data_source_generic_secret.go
Labels: size/XS

#759 Adding uri_sans to pki_secret_backend_cert
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
  website/docs/r/pki_secret_backend_cert.html.md
Labels: enhancement, pki, size/XS

#773 Add missed algorithm RSA-3072 in Transit backend
  vault/resource_transit_secret_backend_key.go
  website/docs/r/transit_secret_backend_key.html.md
Labels: bug, size/XS, transit

#851 There is no "write" capability
  website/docs/r/policy.html.md
Labels: documentation, size/XS, waiting-response

#857 Clarify aws_auth_backend_role docs
  website/docs/r/aws_auth_backend_role.html.md
Labels: documentation, resource/aws_auth, size/XS
