Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-12, with the labels that each got.

#924 Upgrade github.com/hashicorp/go-retryablehttp dependency to retry HTTP 429 responses from Vault
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: dependencies, size/XL

#877 Add support for the bound_claims_type attribute in the JWT auth
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/S

#928 Skip flaky test TestAccIdentityGroupMemberEntityIdsNonExclusive
  vault/resource_identity_group_member_entity_ids_test.go
Labels: size/XS

#923 Add Nomad secret backend
  util/util.go
  vault/data_source_nomad_credentials.go
  vault/data_source_nomad_credentials_test.go
  vault/provider.go
  vault/resource_nomad_secret_backend.go
  vault/resource_nomad_secret_backend_test.go
  vault/resource_nomad_secret_role.go
  vault/resource_nomad_secret_role_test.go
  website/docs/d/nomad_access_token.html.md
  website/docs/r/nomad_secret_backend.html.md
  website/docs/r/nomad_secret_role.html.md
Labels: documentation, size/XXL

#929 Tune mount when description is changed
  vault/resource_mount.go
  vault/resource_mount_test.go
  vault/resource_ssh_secret_backend_ca_test.go
Labels: size/S

#931 Add sts_region for AWS auth backend
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
  website/docs/r/aws_auth_backend_client.html.md
Labels: documentation, size/S

#891 Add vault_azure_secret_backend_role support for azure_groups
  README.md
  vault/resource_azure_secret_backend_role.go
  vault/resource_azure_secret_backend_role_test.go
  website/docs/r/azure_secret_backend_role.html.md
Labels: documentation, size/M

#815 Allow client_id to be configured on vault_identity_oidc_role resources
  vault/resource_identity_oidc_role.go
  vault/resource_identity_oidc_role_test.go
  website/docs/r/identity_oidc_role.html.md
Labels: documentation, size/M
