Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-02, with the labels that each got.

#650 Add support for standard auth mount tune configuration to vault_auth_backend resource
  vault/resource_auth_backend.go
  vault/resource_auth_backend_test.go
Labels: size/L

#659 Use set connection_url when available instead of value read for API response for MongoDB plugin
  vault/resource_database_secret_backend_connection.go
Labels: size/XS

#662 Automate MongoDB tests as part of the CircleCI build
  .circleci/config.yml
  vault/resource_database_secret_backend_connection.go
Labels: size/S

#665 Fix reversed argument descriptions
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#672 Clarify required vault capabilities and disable_read usage
  website/docs/r/generic_secret.html.md
Labels: documentation, size/XS

#675 Add missing documentation link to `vault_consul_secret_backend_role`
  website/vault.erb
Labels: documentation, size/XS

#676 Update database_secret_backend_role.md
  website/docs/r/database_secret_backend_role.md
Labels: documentation, size/XS
