Repository hashicorp/terraform-provider-vault, pull requests merged in 2020-04, with the labels that each got.

#704 Elasticsearch support in vault_database_secret_backend_connection
  .test-env
  docker-compose.yaml
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/L

#728 Fix tests
  go.mod
  go.sum
  vault/resource_database_secret_backend_static_role_test.go
  vendor/github.com/go-sql-driver/mysql/.gitignore
  vendor/github.com/go-sql-driver/mysql/.travis.yml
  vendor/github.com/go-sql-driver/mysql/AUTHORS
  vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
  vendor/github.com/go-sql-driver/mysql/LICENSE
  vendor/github.com/go-sql-driver/mysql/README.md
  vendor/github.com/go-sql-driver/mysql/auth.go
  vendor/github.com/go-sql-driver/mysql/buffer.go
  vendor/github.com/go-sql-driver/mysql/collations.go
  vendor/github.com/go-sql-driver/mysql/conncheck.go
  vendor/github.com/go-sql-driver/mysql/conncheck_dummy.go
  vendor/github.com/go-sql-driver/mysql/connection.go
  vendor/github.com/go-sql-driver/mysql/connector.go
  vendor/github.com/go-sql-driver/mysql/const.go
  vendor/github.com/go-sql-driver/mysql/driver.go
  vendor/github.com/go-sql-driver/mysql/dsn.go
  vendor/github.com/go-sql-driver/mysql/errors.go
  vendor/github.com/go-sql-driver/mysql/fields.go
  vendor/github.com/go-sql-driver/mysql/go.mod
  vendor/github.com/go-sql-driver/mysql/infile.go
  vendor/github.com/go-sql-driver/mysql/nulltime.go
  vendor/github.com/go-sql-driver/mysql/nulltime_go113.go
  vendor/github.com/go-sql-driver/mysql/nulltime_legacy.go
  vendor/github.com/go-sql-driver/mysql/packets.go
  vendor/github.com/go-sql-driver/mysql/result.go
  vendor/github.com/go-sql-driver/mysql/rows.go
  vendor/github.com/go-sql-driver/mysql/statement.go
  vendor/github.com/go-sql-driver/mysql/transaction.go
  vendor/github.com/go-sql-driver/mysql/utils.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#732 update multiple namespace support example to include name
  website/docs/index.html.markdown
Labels: documentation, size/XS

#737 Move provider to separate package
  main.go
  schema/provider.go
  vault/provider.go
  vault/provider_test.go
Labels: size/S
