Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-06, with the labels that each got.

#975 Docs: Update aws_auth_backend_login with recent/working examples
  website/docs/r/aws_auth_backend_login.html.md
Labels: documentation, size/S

#973 [doc] Add optional argument `version` for KV v2 backend
  website/docs/d/generic_secret.html.md
Labels: documentation, size/XS

#1067 Fixing missing mandatory value in example
  website/docs/d/azure_access_credentials.html.md
Labels: documentation, size/XS

#1066 Add doc for auth_type method
  website/docs/index.html.markdown
Labels: documentation, size/S

#1070 add vault_mount PKI example
  website/docs/r/mount.html.md
Labels: documentation, size/XS

#1011 add vault_gcp_auth_backend_role data source
  vault/data_source_gcp_auth_backend_role.go
  vault/data_source_gcp_auth_backend_role_test.go
  vault/provider.go
  website/docs/d/gcp_auth_backend_role.md
Labels: documentation, size/XL

#1065 Migrate most GitHub HashiBot behaviors to GitHub Actions
  .github/labeler-issue-triage.yml
  .github/labeler-pull-request-triage.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/M

#1071 Clean up PKI examples
  website/docs/r/pki_secret_backend_cert.html.md
  website/docs/r/pki_secret_backend_config_ca.html.md
  website/docs/r/pki_secret_backend_config_urls.html.md
  website/docs/r/pki_secret_backend_crl_config.html.md
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
  website/docs/r/pki_secret_backend_intermediate_set_signed.html.md
  website/docs/r/pki_secret_backend_role.html.md
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: documentation, size/M

#1075 Migrate from GitHub HashiBot pull_request_size_labeler behavior to GitHub Actions
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/S

#1076 Fix bad merge conflict resolution
  vault/provider.go
Labels: size/XS

#1078 RabbitMQ doc fix - path defaults to `rabbitmq`, not `aws`.
  website/docs/r/rabbitmq_secret_backend.html.md
Labels: documentation, size/XS

#1074 Add support for ldap client_tls settings
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
Labels: size/L

#992 Update vault_database_secret_backend_connection docs for mongodbatlas option
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/XS

#987 Add identity details to error messages
  vault/data_identity_entity.go
  vault/data_identity_group.go
Labels: size/XS

#948 Max leases quota
  vault/provider.go
  vault/resource_quota_lease_count.go
  vault/resource_quota_lease_count_test.go
  website/docs/r/quota_lease_count.md
  website/vault.erb
Labels: documentation, size/XL
