Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-09, with the labels that each got.

#1139 Add raft_snapshot_agent_config resource.
  vault/provider.go
  vault/resource_raft_snapshot_agent_config.go
  vault/resource_raft_snapshot_agent_config_test.go
  website/docs/r/raft_snapshot_agent_config.html.md
Labels: documentation, size/XL

#1158 Fix sample code in documentation for `vault_terraform_cloud_secret_backend`
  website/docs/r/terraform_cloud_secret_backend.md
Labels: documentation, size/XS

#1134 [FIX] resource/vault_identity_group external member_entity_ids & member_group_ids
  vault/resource_identity_group.go
Labels: size/XS

#1168 Fix typo in the resource vault_ad_secret_backend_library
  website/docs/r/ad_secret_backend_library.html.md
Labels: documentation, size/XS

#1171 docs: jwt auth role bound_claims list format
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/XS

#1177 incorrect role in sample code
  website/docs/r/database_secret_backend_role.md
Labels: documentation, size/XS

#1173 Add provider tests and fix S3 secret issue
  vault/resource_raft_snapshot_agent_config.go
  vault/resource_raft_snapshot_agent_config_test.go
Labels: size/M
