Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-01, with the labels that each got.

#935 Add import doc for K8s auth backend
  website/docs/r/kubernetes_auth_backend_config.md
Labels: documentation, size/XS

#937 docs: Add Accessor Attribute for jwt_auth_backend
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/XS

#940 Fix typo on vault_policy_document page
  website/docs/d/policy_document.md
Labels: documentation, size/XS

#941 doc: fix typo in PKI
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
Labels: documentation, size/XS

#910 Mr miles ca cert
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_test.go
  website/docs/r/consul_secret_backend.html.md
Labels: documentation, size/M

#945 docs: Added "Import" section for identity_entity_alias
  website/docs/r/identity_entity_alias.html.md
Labels: documentation, size/XS

#927 Adding new resource for password policy
  vault/password_policy.go
  vault/provider.go
  vault/resource_password_policy.go
  vault/resource_password_policy_test.go
  website/docs/r/password_policy.html.md
Labels: documentation, size/L

#943 Provider config
  vault/resource_jwt_auth_backend.go
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/XS

#950 Fix consul secret backend formatting error
  vault/resource_consul_secret_backend.go
Labels: size/XS
