Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-11, with the labels that each got.

#1200 [VAULT-3380] Add field to disable comma separation on `bound_claims` in `jwt_auth_backend_role` resource
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
Labels: size/M

#1212 Update Changelog to include #1200 changes
  CHANGELOG.md
Labels: size/XS

#1214 transform/template: add encode_format and decode_formats options.
  CHANGELOG.md
  cmd/generate/main.go
  generated/resources/transform/template/name.go
  generated/resources/transform/template/name_test.go
  website/docs/r/transform_template.html.md
  website/vault.erb
Labels: documentation, size/L

#770 Fix time format bug for generic secret data source
  vault/data_source_generic_secret.go
Labels: bug, size/XS

#1217 Update Jira sync configuration
  .github/workflows/jira.yaml
Labels: size/XS

#1216 Update changelog and add tests for the generic_secret data source.
  CHANGELOG.md
  vault/data_source_generic_secret.go
  vault/data_source_generic_secret_test.go
  website/docs/d/generic_secret.html.md
Labels: documentation, size/S

#1210 Add Raft Autopilot Configuration Resource
  vault/provider.go
  vault/resource_raft_autopilot.go
  vault/resource_raft_autopilot_test.go
  website/docs/r/raft_autopilot.html.md
Labels: documentation, size/L

#1225 Add changelog for v2.24.1
  CHANGELOG.md
Labels: size/XS

#1220 Update `CHANGELOG.md` with the Raft Autopilot resource merged in #1210
  CHANGELOG.md
Labels: size/XS

#1224 Add import documentation and examples
  website/docs/r/namespace.html.md
Labels: documentation, size/S

#1222 Add a `TestRaftPrecheck` in util to enable Raft tests using env var
  .circleci/config.yml
  vault/resource_raft_autopilot_test.go
Labels: size/XS

#1228 documentation - update vault_token_auth_backend_role example
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/XS

#1231 Ensure disable_iss_validation is properly set.
  vault/resource_kubernetes_auth_backend_config.go
  vault/resource_kubernetes_auth_backend_config_test.go
Labels: size/XS

#1230 Handle nil cidr_list from Vault response in approle_auth_backend_secret_id
  vault/resource_approle_auth_backend_role_secret_id.go
Labels: size/XS

#1229 Prevent invalid policy_arns from being created.
  util/util.go
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
Labels: size/M

#1233 Update OpenAPI
  testdata/openapi.json
Labels: size/XL

#1234 Release v3.0.1
  CHANGELOG.md
Labels: size/XS

#1219 fix vault_ad_secret_role resource documentation
  website/docs/r/ad_secret_role.html.md
  website/vault.erb
Labels: documentation, size/XS

#978 docs: update example usage in vault_approle_auth_backend_role_secret_id
  website/docs/r/approle_auth_backend_role_secret_id.html.md
Labels: documentation, size/XS

#1238 Add support for patch to vault_policy_document
  CHANGELOG.md
  vault/data_source_policy_document.go
  vault/data_source_policy_document_test.go
Labels: size/XS

#1121 Add support for influxdb database connection
  docker-compose.yaml
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/L
