Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-12, with the labels that each got.

#1243 Update Changelog after InfluxDB support update
  CHANGELOG.md
Labels: size/XS

#775 Create optional provider config setting for using or disabling the child token
  vault/provider.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#1250 Encrypt logged HTTP secret header values.
  helper/transport.go
  vault/provider.go
Labels: size/M

#1252 Update skip_child_token docs.
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1236 Fix incorrect resource name in changelog
  CHANGELOG.md
Labels: size/XS

#1245 Fix `nil` panic with `vault_identity_group_policies`
  vault/resource_identity_group_policies.go
Labels: bug, size/XS

#1258 Update Golang Docker image in CircleCI
  .circleci/config.yml
Labels: size/XS

#1261 Fix vault_approle_auth_backend_role policy example
  website/docs/r/approle_auth_backend_login.html.md
Labels: documentation, size/XS

#1262 Provide better error handling for JSON metadata
  vault/provider.go
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/resource_aws_secret_backend_role.go
  vault/resource_gcp_secret_backend.go
  vault/resource_generic_endpoint.go
  vault/resource_generic_secret.go
Labels: size/M

#1014 treat non-json values as not matching
  util/util.go
Labels: size/XS

#1244 Add more configuration options for JWT Auth Backend
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/S, feature-parity

#1259 Add contained_db field to mssql db secret backend
  .circleci/config.yml
  go.mod
  go.sum
  vault/provider.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, dependencies, size/XL

#1254 Include support to delete key metadata for kv-v2 generic secrets
  CHANGELOG.md
  vault/import_generic_secret_test.go
  vault/resource_generic_secret.go
  vault/resource_generic_secret_test.go
  website/docs/r/generic_secret.html.md
Labels: documentation, size/L, feature-parity

#1263 Add support for retrying identity entity reads
  go.mod
  util/util.go
  vault/provider.go
  vault/resource_identity_entity.go
  vault/resource_identity_entity_policies.go
  vault/resource_identity_entity_policies_test.go
  vault/resource_identity_entity_test.go
  vault/resource_identity_group.go
  vault/resource_identity_group_member_entity_ids.go
  vault/resource_identity_group_member_entity_ids_test.go
  vault/resource_identity_group_policies.go
  vault/resource_identity_group_policies_test.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1264 Drop runtime team from Jira GH workflow
  .github/workflows/jira.yaml
Labels: size/XS

#1265 Update Changelog with unreleased 3.1.0 features
  CHANGELOG.md
Labels: size/XS

#1266 Update changelog for v3.1.0
  CHANGELOG.md
Labels: size/XS

#1267 Set timeout to 5m for non-acceptance tests.
  GNUmakefile
Labels: size/XS

#1270 Set parent client's token on its clone
  CHANGELOG.md
  vault/resource_identity_entity.go
Labels: size/XS

#1271 Include PR link in changelog
  CHANGELOG.md
Labels: size/XS

#1272 Update vault/api for token cloning and other fixes
  go.mod
  go.sum
  util/util.go
  vault/provider.go
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/resource_identity_entity.go
  vault/resource_token.go
Labels: dependencies, size/XS

#1273 Fix invalid link syntax in changelog
  CHANGELOG.md
Labels: size/XS

#1268 Run test make target before acceptance tests
  .circleci/config.yml
  vault/resource_database_secret_backend_connection_test.go
Labels: size/XS
