Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-03, with the labels that each got.

#869 Support allowed_domains_template option for vault_pki_secret_backend_role
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, pki, size/XS

#1002 don't send empty "name" to identity/group
  vault/resource_identity_group.go
Labels: size/XS

#974 Add docs to accompany the release of the Terraform Cloud/Enterprise TFVP support.
  website/docs/r/terraform_cloud_secret_backend.md
  website/docs/r/terraform_cloud_secret_creds.html.md
  website/docs/r/terraform_cloud_secret_role.html.md
Labels: documentation, size/L
