Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-07, with the labels that each got.

#1090 fix: Drop the terraform-providers module replacement.
  GNUmakefile
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
  vendor/modules.txt
Labels: dependencies, size/S

#1085 update token example for proper token encryption usage
  website/docs/r/token.html.md
Labels: documentation, size/XS

#1061 Fix bug where group values not removed
  vault/resource_identity_group.go
Labels: size/S

#977 Docs: identity_group_alias.html.md
  website/docs/r/identity_group_alias.html.md
Labels: documentation, size/XS

#960 Fix bug where provider_config only used strings
  vault/provider_test.go
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
Labels: bug, size/L

#1105 remove an extra blank line
  vault/resource_identity_group.go
Labels: size/XS

#1101 Correct vault_mount documentation
  website/docs/r/mount.html.md
Labels: documentation, size/XS

#1010 Expand PR899 to also cover Entity Groups
  vault/resource_identity_entity.go
  vault/resource_identity_group.go
  website/docs/r/identity_group.html.md
Labels: documentation, size/S

#1114 Revert "Fix bug where provider_config only used strings (#960)"
  vault/provider_test.go
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
Labels: size/L

#1118 Add support for all provider_config types
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  website/docs/r/jwt_auth_backend.html.md
Labels: bug, documentation, size/L

#1125 fix: support importing gcp_auth_backend
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_auth_backend_test.go
Labels: size/M

#1094 Add resource for GCP Static Account
  go.mod
  vault/gcp.go
  vault/provider.go
  vault/resource_gcp_secret_roleset.go
  vault/resource_gcp_secret_roleset_test.go
  vault/resource_gcp_secret_static_account.go
  vault/resource_gcp_secret_static_account_test.go
  website/docs/r/gcp_secret_static_account.html.md
  website/vault.erb
Labels: dependencies, documentation, size/XL
