Repository hashicorp/terraform-provider-vault, pull requests merged in 2021-05, with the labels that each got.

#1009 Create azure secrets backend Update Functionality
  vault/resource_azure_secret_backend.go
  vault/resource_azure_secret_backend_test.go
Labels: size/M

#1050 GCP auth: support nested backend mount paths
  vault/resource_gcp_auth_backend_role.go
  vault/resource_gcp_auth_backend_role_test.go
Labels: size/M

#1022 kubernetes auth role: allow unset audience
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role_test.go
Labels: size/S

#1054 Fix bug where entity values not removed
  vault/resource_identity_entity.go
  vault/resource_identity_entity_test.go
Labels: bug, size/M

#1047 Userpass syntax tweak
  website/docs/r/generic_endpoint.html.md
Labels: documentation, size/XS

#1039 provider: Bump minimum Go version to 1.16
  .circleci/config.yml
  .go-version
  README.md
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/M
