Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-11, with the labels that each got.

#1653 Temporarily skip azure secrets tests on vault-1.12
  .github/workflows/build.yml
  Makefile
  README.md
  internal/provider/meta.go
  testutil/testutil.go
  vault/resource_azure_secret_backend_test.go
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_consul_secret_backend_test.go
  vault/resource_kubernetes_auth_backend_config_test.go
  vault/testhelpers_test.go
Labels: size/L

#1639 CI: test against vault-1.12.0
  .github/workflows/build.yml
Labels: size/XS

#1659 Redis - Add TFVP Support
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
  website/docs/r/database_secrets_mount.md
Labels: documentation, size/L

#1661 Update PR "Add Basic Constraints attribute to vault_pki_secret_backend_intermediate_cert_request"
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
Labels: documentation, size/M

#1669 Fix panic while importing MFA Duo resource
  vault/resource_mfa_duo.go
  vault/resource_mfa_duo_test.go
Labels: size/M

#1670 Update changelog for v3.11.0
  CHANGELOG.md
Labels: size/XS

#1680 docs(): update vault_okta_auth_backend documentation
  website/docs/r/okta_auth_backend.html.md
Labels: documentation, size/XS
