Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-04, with the labels that each got.

#1395 Add support for Okta, TOTP and PingID MFA methods
  vault/provider.go
  vault/resource_mfa_okta.go
  vault/resource_mfa_okta_test.go
  vault/resource_mfa_pingid.go
  vault/resource_mfa_pingid_test.go
  vault/resource_mfa_totp.go
  vault/resource_mfa_totp_test.go
  website/docs/r/mfa_okta.html.md
  website/docs/r/mfa_pingid.html.md
  website/docs/r/mfa_totp.html.md
  website/vault.erb
Labels: documentation, size/XL

#1401 Fix typo in cert_auth_backend_role output
  vault/resource_cert_auth_backend_role.go
Labels: size/XS

#1403 Update containerd to v1.6.2
  go.mod
  go.sum
Labels: dependencies, size/L

#1402 Update transit secret key to support auto_rotate_period
  vault/resource_transit_secret_backend_key.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/M

#1399 Add cross-referencing link to Learn tutorials
  website/docs/index.html.markdown
  website/docs/r/auth_backend.html.md
  website/docs/r/policy.html.md
Labels: documentation, size/XS

#1400 Add new database_secrets_mount resource
  .circleci/config.yml
  vault/provider.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  vault/resource_database_secrets_mount.go
  vault/resource_database_secrets_mount_test.go
  vault/resource_mount.go
  website/docs/r/database_secrets_mount.md
  website/vault.erb
Labels: documentation, size/XL

#1404 No longer skip vault "next" tests in CI
  .circleci/config.yml
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_github_auth_backend_test.go
  vault/resource_transit_secret_backend_key_test.go
Labels: size/S

#1408 Migrate Provider Releases from TeamCity to GitHub Actions
  .github/workflows/release.yml
  .goreleaser.yml
  terraform-registry-manifest.json
Labels: size/M

#1410 Prevent 'invalid filename terraform-registry-manifest.json' errors during release
  .goreleaser.yml
Labels: size/XS

#1411 Add PKI certificate revocation support
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
  website/docs/r/pki_secret_backend_cert.html.md
Labels: documentation, size/L

#1409 Fix issue where group member entities were lost
  vault/resource_identity_group.go
  vault/resource_identity_group_member_entity_ids.go
  vault/resource_identity_group_member_entity_ids_test.go
  website/docs/r/identity_group_member_entity_ids.html.md
Labels: documentation, size/XL

#1413 Add new allowed_user_key_config field
  CHANGELOG.md
  go.mod
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, dependencies, size/XL

#1414 Add new field `with_lease_start_time` to `data.vault_generic_secret`
  CHANGELOG.md
  vault/data_source_generic_secret.go
  website/docs/d/generic_secret.html.md
Labels: documentation, size/S

#1417 doc(fix): fix typo in vault_aws_auth_backend_login
  website/docs/r/aws_auth_backend_login.html.md
Labels: documentation, size/XS

#1416 add token_ prefix to example
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/XS

#1145 feat: support for VAULT_TLS_SERVER_NAME
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1420 Docs: drop unsupported fields for r/pki-root-sign-intermediate
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
Labels: documentation, size/XS

#1421 Update changelog with missing entry for MFA resources
  CHANGELOG.md
Labels: size/XS

#1422 Update changelog and docs for release
  CHANGELOG.md
  website/docs/r/database_secrets_mount.md
Labels: documentation, size/M

#1375 Removes duplicate certificate from certificate_bundle in vault_pki_secret_backend_root_sign_intermediate
  go.mod
  go.sum
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
Labels: dependencies, size/L

#1377 Add role_id computed field to aws role
  vault/resource_aws_auth_backend_role.go
  vault/resource_aws_auth_backend_role_test.go
  website/docs/r/aws_auth_backend_role.html.md
Labels: documentation, size/XS

#1427 Temporarily skip some PKI root sign tests
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
Labels: size/XS

#1425 Correctly document token_num_uses for all resources
  website/docs/r/alicloud_auth_backend_role.md
  website/docs/r/approle_auth_backend_role.html.md
  website/docs/r/aws_auth_backend_role.html.md
  website/docs/r/azure_auth_backend_role.html.md
  website/docs/r/cert_auth_backend_role.html.md
  website/docs/r/gcp_auth_backend_role.html.md
  website/docs/r/github_auth_backend.html.md
  website/docs/r/jwt_auth_backend_role.html.md
  website/docs/r/kubernetes_auth_backend_role.html.md
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/M

#1428 Update the way that the certificate bundle is generated
  CHANGELOG.md
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
Labels: size/XL

#791 Update pki_secret_backend_role to allow key_type "any"
  vault/resource_pki_secret_backend_role.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/XS
