Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-03, with the labels that each got.

#1366 Add support for Consul roles
  testutil/testutil.go
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_github_auth_backend_test.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/r/consul_secret_backend_role.html.md
Labels: documentation, size/L

#1367 Add support for Consul namespaces and partitions
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  website/docs/r/consul_secret_backend_role.html.md
Labels: documentation, size/M

#1368 Merge Client and Provider resources to OIDC feature branch
  vault/data_identity_oidc_client_creds.go
  vault/provider.go
  vault/resource_identity_oidc_assignment_test.go
  vault/resource_identity_oidc_client.go
  vault/resource_identity_oidc_client_test.go
  vault/resource_identity_oidc_provider.go
  vault/resource_identity_oidc_provider_test.go
  vault/resource_identity_oidc_scope_test.go
  website/docs/d/identity_oidc_client_creds.html.md
  website/vault.erb
Labels: size/XL

#1382 Update `organization` field to failing GitHub tests
  vault/resource_github_team_test.go
  vault/resource_github_user_test.go
Labels: size/XS

#1381 Rework the credential validation to use azidentity
  CHANGELOG.md
  go.mod
  go.sum
  vault/data_source_azure_access_credentials.go
  vault/data_source_azure_access_credentials_test.go
  website/docs/d/azure_access_credentials.html.md
Labels: documentation, dependencies, size/L

#1383 Retry the mount tune operation after remount.
  vault/resource_mount.go
Labels: size/XS

#1363 Add OIDC Provider support to TFVP
  vault/data_identity_oidc_client_creds.go
  vault/data_identity_oidc_client_creds_test.go
  vault/data_identity_oidc_openid_config.go
  vault/data_identity_oidc_openid_config_test.go
  vault/data_identity_oidc_public_keys.go
  vault/data_identity_oidc_public_keys_test.go
  vault/provider.go
  vault/resource_identity_oidc_assignment.go
  vault/resource_identity_oidc_assignment_test.go
  vault/resource_identity_oidc_client.go
  vault/resource_identity_oidc_client_test.go
  vault/resource_identity_oidc_provider.go
  vault/resource_identity_oidc_provider_test.go
  vault/resource_identity_oidc_scope.go
  vault/resource_identity_oidc_scope_test.go
  website/docs/d/identity_oidc_client_creds.html.md
  website/docs/d/identity_oidc_openid_config.html.md
  website/docs/d/identity_oidc_public_keys.html.md
  website/docs/r/identity_oidc_assignment.html.md
  website/docs/r/identity_oidc_client.html.md
  website/docs/r/identity_oidc_provider.html.md
  website/docs/r/identity_oidc_scope.html.md
  website/vault.erb
Labels: documentation, size/XL

#1384 Allow for overriding the tenant and subscription IDs.
  CHANGELOG.md
  vault/data_source_azure_access_credentials.go
  website/docs/d/azure_access_credentials.html.md
Labels: documentation, size/M

#1386 Skip SSH role tests
  vault/resource_ssh_secret_backend_role_test.go
Labels: size/XS

#1385 Update Changelog with 1.10 Features and Improvements
  CHANGELOG.md
Labels: size/XS

#1342 Release for vault-1.10
  .circleci/config.yml
  CHANGELOG.md
  testutil/testutil.go
  util/util.go
  util/util_test.go
  vault/auth_token.go
  vault/data_identity_oidc_client_creds.go
  vault/data_identity_oidc_client_creds_test.go
  vault/data_identity_oidc_openid_config.go
  vault/data_identity_oidc_openid_config_test.go
  vault/data_identity_oidc_public_keys.go
  vault/data_identity_oidc_public_keys_test.go
  vault/provider.go
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  vault/resource_github_auth_backend.go
  vault/resource_github_auth_backend_test.go
  vault/resource_github_team_test.go
  vault/resource_github_user_test.go
  vault/resource_identity_oidc_assignment.go
  vault/resource_identity_oidc_assignment_test.go
  vault/resource_identity_oidc_client.go
  vault/resource_identity_oidc_client_test.go
  vault/resource_identity_oidc_provider.go
  vault/resource_identity_oidc_provider_test.go
  vault/resource_identity_oidc_scope.go
  vault/resource_identity_oidc_scope_test.go
  vault/resource_transit_secret_backend_key.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/d/identity_oidc_client_creds.html.md
  website/docs/d/identity_oidc_openid_config.html.md
  website/docs/d/identity_oidc_public_keys.html.md
  website/docs/r/consul_secret_backend_role.html.md
  website/docs/r/database_secret_backend_connection.md
  website/docs/r/github_auth_backend.html.md
  website/docs/r/identity_oidc_assignment.html.md
  website/docs/r/identity_oidc_client.html.md
  website/docs/r/identity_oidc_provider.html.md
  website/docs/r/identity_oidc_scope.html.md
  website/docs/r/transit_secret_backend_key.html.md
  website/vault.erb
Labels: documentation, size/XL

#1391 Fix panic when tenant_id and subscription are specified
  CHANGELOG.md
  vault/data_source_azure_access_credentials.go
  website/docs/d/azure_access_credentials.html.md
Labels: documentation, size/S

#1393 Jira Sync: transition to "Re-Triage" on issue reopen.
  .github/workflows/jira.yaml
Labels: size/XS

#1394 Document Vault Enterprise 1.10 CCC mitigation
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1276 r/rabbitmq_secret_backend - add `password_policy` and `username_template` arguments.
  vault/resource_rabbitmq_secret_backend.go
  vault/resource_rabbitmq_secret_backend_test.go
  website/docs/r/rabbitmq_secret_backend.html.md
Labels: documentation, size/M, ecosystem, feature-parity

#1396 Update docs for #1166
  CHANGELOG.md
  website/docs/r/approle_auth_backend_role_secret_id.html.md
Labels: documentation, size/XS

#1397 Update changelog for #1276
  CHANGELOG.md
Labels: size/XS

#1398 Add caveats section for d/azure_access_credentials
  website/docs/d/azure_access_credentials.html.md
Labels: documentation, size/XS
