Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-10, with the labels that each got.

#1596 Add redis elasticache database plugin support
  codegen/generate.go
  vault/data_source_kubernetes_credentials_test.go
  vault/gcp.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
  website/docs/r/database_secrets_mount.md
Labels: documentation, size/L

#1621 docs: document the `disable_remount` field
  website/docs/r/ad_secret_backend.html.md
  website/docs/r/auth_backend.html.md
  website/docs/r/aws_secret_backend.html.md
  website/docs/r/azure_secret_backend.html.md
  website/docs/r/consul_secret_backend.html.md
  website/docs/r/gcp_auth_backend.html.md
  website/docs/r/gcp_secret_backend.html.md
  website/docs/r/github_auth_backend.html.md
  website/docs/r/jwt_auth_backend.html.md
  website/docs/r/kmip_secret_backend.html.md
  website/docs/r/ldap_auth_backend.html.md
  website/docs/r/nomad_secret_backend.html.md
  website/docs/r/okta_auth_backend.html.md
  website/docs/r/rabbitmq_secret_backend.html.md
  website/docs/r/terraform_cloud_secret_backend.md
Labels: documentation, size/S

#1620 Add support for login MFA resources
  internal/consts/consts.go
  internal/identity/mfa/duo.go
  internal/identity/mfa/login_enforcement.go
  internal/identity/mfa/mfa.go
  internal/identity/mfa/okta.go
  internal/identity/mfa/ping_id.go
  internal/identity/mfa/totp.go
  internal/provider/meta.go
  internal/provider/schema_util.go
  internal/provider/validators.go
  internal/provider/validators_test.go
  util/util.go
  util/util_test.go
  vault/provider.go
  vault/resource_identity_entity_alias.go
  vault/resource_identity_mfa_duo_test.go
  vault/resource_identity_mfa_login_enforcement_test.go
  vault/resource_identity_mfa_okta_test.go
  vault/resource_identity_mfa_pingid_test.go
  vault/resource_identity_mfa_totp_test.go
  vault/resource_managed_keys.go
  vault/resource_managed_keys_test.go
  website/docs/r/identity_mfa_duo.html.md
  website/docs/r/identity_mfa_login_enforcement.html.md
  website/docs/r/identity_mfa_okta.html.md
  website/docs/r/identity_mfa_pingid.html.md
  website/docs/r/identity_mfa_totp.html.md
  website/vault.erb
Labels: documentation, size/XL

#1622 Fix erroneous persistent diff in the vault_token resource.
  internal/consts/consts.go
  vault/resource_token.go
  vault/resource_token_test.go
Labels: size/L

#1623 Update change log for 3.9.0 release
  CHANGELOG.md
Labels: size/XS

#1567 fix identityGroupExists
  vault/resource_identity_group.go
Labels: size/XS

#1625 Use the correct AWS login headers within auth_generic
  internal/consts/consts.go
  internal/provider/auth_aws.go
Labels: size/XS

#1626 update changelog for v3.9.1 release
  CHANGELOG.md
Labels: size/XS

#1628 Fix OIDC login initialization check
  internal/provider/auth_oidc.go
Labels: size/XS

#1631 Ensure all AuthLogin instances are validated on call to Login().
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_aws_test.go
  internal/provider/auth_azure.go
  internal/provider/auth_azure_test.go
  internal/provider/auth_cert.go
  internal/provider/auth_cert_test.go
  internal/provider/auth_gcp.go
  internal/provider/auth_gcp_test.go
  internal/provider/auth_generic.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_oci.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_oidc.go
  internal/provider/auth_oidc_test.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_userpass.go
  internal/provider/auth_userpass_test.go
Labels: size/XL

#1637 Ensure that namespaced github auth mount is destroyed
  internal/consts/consts.go
  vault/resource_github_auth_backend.go
  vault/resource_github_auth_backend_test.go
  vault/testhelpers_test.go
Labels: size/XL

#1638 Update some backend tests to use testCheckMountDestroyed
  Makefile
  internal/consts/consts.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_backend_test.go
  vault/resource_azure_secret_backend_test.go
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_test.go
  vault/resource_gcp_secret_backend.go
  vault/resource_gcp_secret_backend_test.go
  vault/resource_jwt_auth_backend_test.go
  vault/resource_terraform_cloud_secret_backend.go
  vault/resource_terraform_cloud_secret_backend_test.go
Labels: size/XL

#1645 Complete the OIDC login flow via a local web browser.
  go.mod
  go.sum
  internal/provider/auth_oidc.go
  internal/provider/auth_oidc_test.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1646 Support configuring vault version handling.
  internal/consts/consts.go
  internal/provider/meta.go
  internal/provider/meta_test.go
  internal/provider/validators.go
  internal/provider/validators_test.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/L

#1630 Add support for externally managed Group Member IDs to Vault Identity Group
  internal/consts/consts.go
  internal/identity/entity/entity.go
  internal/identity/group/group.go
  internal/identity/group/testhelpers.go
  internal/provider/locker.go
  vault/provider.go
  vault/resource_identity_entity.go
  vault/resource_identity_entity_alias.go
  vault/resource_identity_entity_policies.go
  vault/resource_identity_entity_policies_test.go
  vault/resource_identity_entity_test.go
  vault/resource_identity_group.go
  vault/resource_identity_group_member_entity_ids.go
  vault/resource_identity_group_member_entity_ids_test.go
  vault/resource_identity_group_member_group_ids.go
  vault/resource_identity_group_member_group_ids_test.go
  vault/resource_identity_group_policies.go
  vault/resource_identity_group_policies_test.go
  vault/resource_identity_group_test.go
  vault/resource_identity_oidc_key.go
  vault/resource_identity_oidc_key_allowed_client_id.go
  website/docs/r/identity_group.html.md
  website/docs/r/identity_group_member_group_ids.html.md
  website/vault.erb
Labels: documentation, size/XL

#1647 Update changelog for v3.10.0
  CHANGELOG.md
Labels: size/XS

#1648 Fix GCP auth with service account credentials
  internal/provider/auth_gcp.go
  internal/provider/auth_gcp_test.go
Labels: size/XS

#1651 Update the TFC tests to be less revealing
  vault/resource_terraform_cloud_secret_creds_test.go
  vault/resource_terraform_cloud_secret_role_test.go
Labels: size/S

#1652 Use the canonical scope constant from the api/iam package.
  internal/provider/auth_gcp.go
Labels: size/XS

#1650 Add support for setting deletion_allowed on a transformation
  Makefile
  generated/datasources/transform/decode/role_name_test.go
  generated/datasources/transform/encode/role_name_test.go
  generated/resources/transform/alphabet/name_test.go
  generated/resources/transform/transformation/name.go
  generated/resources/transform/transformation/name_test.go
  internal/consts/consts.go
  internal/provider/meta.go
  website/docs/r/transform_transformation.html.md
  website/vault.erb
Labels: documentation, size/L
