Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-12, with the labels that each got.

#1678 Set AWS credentials sensitive
  vault/data_source_aws_access_credentials.go
Labels: size/XS

#1677 fix KVv2 data source when specifying a version
  vault/data_source_kv_secret_v2.go
  vault/data_source_kv_secret_v2_test.go
Labels: size/M

#1692 Docs: improve bound_audiences documentation for jwt role
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/XS

#1701 Ensure that vault_kv_secret_backend_v2's mount is correctly imported
  vault/resource_kv_secret_backend_v2.go
  vault/resource_kv_secret_backend_v2_test.go
  website/docs/d/kv_secret_v2.html.md
  website/docs/r/kv_secret_backend_v2.html.md
Labels: documentation, size/S

#1708 Ensure duplicate alias names are handled properly in LookupEntityAlias
  .github/workflows/build.yml
  internal/identity/entity/entity.go
  internal/identity/entity/entity_test.go
  testutil/testutil.go
Labels: size/S

#1682 Fix removed MSGraph param in Azure Secrets
  vault/resource_azure_secret_backend.go
  vault/resource_azure_secret_backend_test.go
  website/docs/r/azure_secret_backend.html.md
Labels: documentation, size/L

#1704 Add parameters to resource vault_pki_secret_backend_crl_config
  vault/resource_pki_secret_backend_crl_config.go
  vault/resource_pki_secret_backend_crl_config_test.go
  website/docs/r/pki_secret_backend_crl_config.html.md
Labels: documentation, size/L
