Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-07, with the labels that each got.

#1529 Update *kv_secrets* resources to support namespaces
  vault/data_source_kv_secret.go
  vault/data_source_kv_secret_v2.go
  vault/data_source_kv_secrets_list.go
  vault/data_source_kv_secrets_list_v2.go
  vault/data_source_kv_subkeys_v2.go
  vault/resource_kv_secret.go
  vault/resource_kv_secret_backend_v2.go
  vault/resource_kv_secret_v2.go
Labels: size/M

#1539 Add k8s-secrets docs to the sidebar
  website/docs/r/kubernetes_secret_backend.html.md
  website/docs/r/kubernetes_secret_backend_role.html.md
  website/vault.erb
Labels: documentation, size/M

#1518 Add support for Consul secrets engine enhancements
  .github/workflows/build.yml
  README.md
  go.mod
  testutil/testutil.go
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  website/docs/r/consul_secret_backend_role.html.md
Labels: documentation, dependencies, size/L

#1515 Adds support for kubernetes secrets engine
  internal/consts/consts.go
  vault/data_source_kubernetes_credentials.go
  vault/data_source_kubernetes_credentials_test.go
  vault/provider.go
  vault/resource_kubernetes_secret_backend.go
  vault/resource_kubernetes_secret_backend_role.go
  vault/resource_kubernetes_secret_backend_role_test.go
  vault/resource_kubernetes_secret_backend_test.go
  vault/resource_mount.go
  website/docs/d/kubernetes_credentials.html.md
  website/docs/r/kubernetes_secret_backend.html.md
  website/docs/r/kubernetes_secret_backend_role.html.md
  website/vault.erb
Labels: documentation, size/XL

#1540 Support testing against vault-enterprise-1.11.0
  .github/workflows/build.yml
  vault/resource_kubernetes_auth_backend_config_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
Labels: size/XS

#1542 Fix bug where some rabbitmq config changes trigger erroneous mount recreation.
  vault/resource_rabbitmq_secret_backend.go
Labels: bug, size/XS

#1544 Drop CircleCI
  .circleci/config.yml
Labels: size/XS

#1543 Fix: support updating secret backend descriptions
  vault/resource_aws_secret_backend.go
  vault/resource_consul_secret_backend.go
  vault/resource_gcp_secret_backend.go
  vault/resource_terraform_cloud_secret_backend.go
Labels: size/XS

#1547 fix: do not validate json on oidc scope template
  vault/resource_identity_oidc_scope.go
  website/docs/r/identity_oidc_scope.html.md
Labels: documentation, size/XS

#1545 Properly set the base64_pem in Vault for Couchbase
  .github/workflows/build.yml
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/L

#1550 Fix: support updating backend descriptions
  .gitignore
  vault/import_mount_test.go
  vault/resource_azure_secret_backend_role.go
  vault/resource_jwt_auth_backend.go
  vault/resource_kubernetes_secret_backend_test.go
  vault/resource_mount.go
  vault/resource_mount_test.go
  vault/resource_okta_auth_backend.go
  vault/resource_rabbitmq_secret_backend.go
Labels: size/M

#1517 Update entity alias creation to use entity lookup api
  vault/resource_identity_entity_alias.go
Labels: size/S

#1548 Fix Import for OIDC Scope resource
  vault/resource_identity_oidc_scope.go
  vault/resource_identity_oidc_scope_test.go
Labels: size/XS

#1552 Move lookupEntityAliasId() to the entity package
  internal/consts/consts.go
  internal/identity/entity/entity.go
  internal/identity/entity/entity_test.go
  vault/data_identity_entity.go
  vault/data_identity_group.go
  vault/resource_identity_entity_alias.go
  vault/resource_identity_entity_alias_test.go
  vault/resource_identity_group_alias.go
  vault/resource_identity_group_alias_test.go
  vault/resource_mfa_duo.go
  vault/resource_mfa_okta.go
  vault/resource_mfa_pingid.go
  vault/resource_mfa_pingid_test.go
Labels: size/XL

#1551 Add version conditional skip for breaking 1.11 k8s test
  vault/resource_kubernetes_auth_backend_config_test.go
Labels: size/XS

#1553 Update change log for 3.8.0 release
  CHANGELOG.md
Labels: size/S

#1554 jira-sync: Close is now Closed
  .github/workflows/jira.yaml
Labels: size/XS
