Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-06, with the labels that each got.

#1477 Drop debug log calls containing the full vault response
  vault/resource_consul_secret_backend.go
  vault/resource_generic_secret.go
  vault/resource_terraform_cloud_secret_backend.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1460 Support LDAP username_as_alias Attribute
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/XS, feature-parity

#1470 Add token metadata support
  vault/resource_token.go
  vault/resource_token_test.go
  website/docs/r/token.html.md
Labels: documentation, size/L

#1471 Validate auth_backend path, disallowing leading/trailing '/'s
  vault/resource_auth_backend.go
  vault/resource_auth_backend_test.go
  website/docs/d/auth_backend.html.md
  website/docs/r/auth_backend.html.md
Labels: documentation, size/XS

#1478 auth/jwt: adds user_claim_json_pointer and max_age to roles
  .github/workflows/build.yml
  vault/resource_jwt_auth_backend_role.go
  vault/resource_jwt_auth_backend_role_test.go
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/M, feature-parity

#1480 Test with terraform 1.2.2 (latest)
  .github/workflows/build.yml
  Makefile
Labels: size/XS

#1088 Added missing import statement for vault_ssh_secret_backend_ca
  website/docs/r/ssh_secret_backend_ca.html.md
Labels: documentation, size/XS

#1483 Update vault lib to v1.10.3
  go.mod
  go.sum
Labels: dependencies, size/L

#1084 Add support for vault_quota_rate_limit interval and block_interval
  vault/resource_quota_rate_limit.go
  vault/resource_quota_rate_limit_test.go
  website/docs/r/quota_rate_limit.md
Labels: documentation, size/M, feature-parity

#1482 auth/gcp: adds custom_endpoint parameter to backend config
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_auth_backend_test.go
  website/docs/r/gcp_auth_backend.html.md
  website/docs/r/jwt_auth_backend_role.html.md
Labels: documentation, size/L, resource/gcp_auth, feature-parity

#1496 Fix: cert-auth allowed_organizational_units handling
  vault/resource_cert_auth_backend_role.go
  vault/resource_cert_auth_backend_role_test.go
  website/docs/r/cert_auth_backend_role.html.md
Labels: documentation, size/M

#1495 PKI: Add support for CPS URL in custom policy identifiers
  internal/pki/policy_identifier.go
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/XL

#1500 Add JWT auth namespace tests
  .github/workflows/build.yml
  vault/resource_jwt_auth_backend_test.go
Labels: size/XL

#1503 Update changelog for v3.7.0
  CHANGELOG.md
Labels: size/S

#1504 Add duplicate field check when adding common schema
  vault/provider.go
Labels: size/S

#1505 add namespace fields in KV docs
  website/docs/d/kv_secret.html.md
  website/docs/d/kv_secret_v2.html.md
  website/docs/d/kv_secrets_list.html.md
  website/docs/d/kv_secrets_list_v2.html.md
  website/docs/d/kv_subkeys_v2.html.md
  website/docs/r/kv_secret.html.md
  website/docs/r/kv_secret_backend_v2.html.md
  website/docs/r/kv_secret_v2.html.md
Labels: documentation, size/S

#1506 Wait for Vault to garbage collect deleted namespaces
  vault/resource_namespace.go
  vault/resource_namespace_test.go
Labels: size/S

#1514 fix docs for vault_identity_oidc_assignment
  website/docs/r/identity_oidc_assignment.html.md
Labels: documentation, size/XS

#1509 Fix documentation for KV resources
  vault/provider.go
  website/docs/d/kv_secret.html.md
  website/docs/d/kv_secret_v2.html.md
  website/docs/d/kv_subkeys_v2.html.md
  website/docs/r/kv_secret_backend_v2.html.md
Labels: documentation, size/S
