Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-09, with the labels that each got.

#1593 Use new semantic version checking for Consul secrets backend logic
  testutil/testutil.go
  vault/resource_ad_secret_backend_test.go
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_consul_secret_backend_test.go
Labels: size/XL

#1597 vault_pki_secret_backend_cert: Report when renewal is pending
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
  website/docs/r/pki_secret_backend_cert.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: documentation, size/M

#1600 Accept data source values in the token field for Consul secrets backend
  vault/resource_consul_secret_backend.go
Labels: size/XS

#1602 docs: Fix vault_kv_secret_backend_v2 delete_version_after example
  website/docs/r/kv_secret_backend_v2.html.md
Labels: documentation, size/XS

#1599 Add first-class auth login config support
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_generic.go
  internal/provider/auth_userpass.go
  internal/provider/auth_userpass_test.go
  internal/provider/meta.go
  internal/provider/schema_util.go
  util/util.go
  util/util_test.go
  vault/provider.go
  vault/provider_test.go
  vault/resource_kubernetes_secret_backend.go
  website/docs/index.html.markdown
Labels: documentation, size/XL, auth-login

#1594 feat: add Mount Migration support to all secrets/auth backends
  internal/consts/consts.go
  internal/provider/meta.go
  internal/provider/meta_test.go
  internal/provider/schema_util.go
  internal/semver/semver.go
  internal/semver/semver_test.go
  util/util.go
  vault/import_auth_backend_test.go
  vault/provider.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_backend_test.go
  vault/resource_auth_backend.go
  vault/resource_auth_backend_test.go
  vault/resource_aws_secret_backend.go
  vault/resource_aws_secret_backend_test.go
  vault/resource_azure_secret_backend.go
  vault/resource_azure_secret_backend_test.go
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_test.go
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_auth_backend_test.go
  vault/resource_gcp_secret_backend.go
  vault/resource_gcp_secret_backend_test.go
  vault/resource_github_auth_backend.go
  vault/resource_github_auth_backend_test.go
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  vault/resource_kmip_secret_backend.go
  vault/resource_kubernetes_secret_backend.go
  vault/resource_kubernetes_secret_backend_role.go
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  vault/resource_managed_keys.go
  vault/resource_nomad_secret_backend.go
  vault/resource_nomad_secret_backend_test.go
  vault/resource_okta_auth_backend.go
  vault/resource_okta_auth_backend_test.go
  vault/resource_rabbitmq_secret_backend.go
  vault/resource_rabbitmq_secret_backend_test.go
  vault/resource_terraform_cloud_secret_backend.go
  vault/resource_terraform_cloud_secret_backend_test.go
Labels: size/XL

#1590 Fix data_source_azure_access_credentials US Government Cloud
  vault/data_source_azure_access_credentials.go
Labels: size/XS

#1605 Add first-class TLS certificates login support
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_cert.go
  internal/provider/auth_cert_test.go
  internal/provider/auth_test.go
  internal/provider/auth_userpass_test.go
  internal/provider/meta.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XL

#1607 Add first-class GCP login support
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_gcp.go
  internal/provider/auth_gcp_test.go
  internal/provider/auth_test.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1608 Add first-class Kerberos login support
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_kerberos_test.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1609 Add first-class Radius login support
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XL

#1613 Add ValidateDiagPath function, validate auth login mount
  internal/provider/auth.go
  internal/provider/validators.go
  internal/provider/validators_test.go
  vault/auth_mount.go
  vault/data_source_kv_secrets_list.go
  vault/provider.go
  vault/resource_auth_backend.go
  vault/resource_auth_backend_test.go
  vault/resource_github_team.go
  vault/resource_jwt_auth_backend.go
  vault/resource_jwt_auth_backend_test.go
  vault/resource_kmip_secret_backend.go
  vault/resource_kmip_secret_role.go
  vault/resource_kmip_secret_scope.go
  vault/resource_mfa_duo.go
  vault/resource_mfa_okta.go
  vault/resource_mfa_pingid.go
  vault/resource_mfa_totp.go
  vault/resource_namespace.go
  vault/resource_namespace_test.go
  vault/resource_pki_secret_backend_role.go
  vault/validators_test.go
Labels: size/XL

#1614 Add first-class OCI login support
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_oci.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_test.go
  internal/provider/validators.go
  internal/provider/validators_test.go
  testutil/testutil.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1615 Add first-class OIDC andJWT login support
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_oidc.go
  internal/provider/auth_oidc_test.go
  internal/provider/schema_util.go
  internal/provider/validators.go
  internal/provider/validators_test.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1617 Add first-class Azure login support
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_azure.go
  internal/provider/auth_azure_test.go
  internal/provider/auth_gcp.go
  internal/provider/auth_generic.go
  internal/provider/auth_jwt.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_radius.go
  internal/provider/auth_test.go
  internal/provider/auth_userpass.go
  website/docs/index.html.markdown
Labels: documentation, size/XL, auth-login

#1618 Rework first-class AWS login support
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/auth_aws.go
  internal/provider/auth_aws_test.go
  internal/provider/auth_generic.go
  internal/provider/meta.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1579 add kv-v2 write retry
  vault/resource_generic_secret.go
Labels: size/XS
