Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-02, with the labels that each got.

#1330 Ensure that the ca_chain is populated, add new certificate_bundle field to pki_secret_backend_root_sign_intermediate
  .circleci/config.yml
  CHANGELOG.md
  GNUmakefile
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  website/docs/r/pki_secret_backend_intermediate_set_signed.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
Labels: documentation, size/XL

#1335 Add support for settng use_microsoft_graph_api in r/azure_secret_backend
  CHANGELOG.md
  vault/resource_azure_secret_backend.go
  vault/resource_azure_secret_backend_test.go
  website/docs/r/azure_secret_backend.html.md
Labels: documentation, size/L

#1336 Add alias_name_source to r/d/kubernetes_auth_backend_role
  CHANGELOG.md
  vault/data_source_kubernetes_auth_backend_role.go
  vault/data_source_kubernetes_auth_backend_role_test.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role_test.go
  website/docs/d/kubernetes_auth_backend_role.md
  website/docs/r/kubernetes_auth_backend_role.html.md
Labels: documentation, size/L

#1126 Add allowed_entity_aliases to token role
  vault/resource_token_auth_backend_role.go
  vault/resource_token_auth_backend_role_test.go
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/S, feature-parity

#1337 Fix persistent diff for kubernetes_ca_cert in k8s-auth-config
  CHANGELOG.md
  vault/data_source_kubernetes_auth_backend_config_test.go
  vault/resource_kubernetes_auth_backend_config.go
  vault/resource_kubernetes_auth_backend_config_test.go
Labels: size/M

#1340 Prevent rotate root test from breaking the other MySQL tests
  vault/resource_database_secret_backend_connection_test.go
Labels: size/S

#1176 Add support for case_sensitive_names in the vault_ldap_auth_backend
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/S, feature-parity

#1341 Restore formatter, and length for AD secrets engine.
  vault/resource_ad_secret_backend.go
  website/docs/guides/version_3_upgrade.html.markdown
  website/docs/r/ad_secret_backend.html.md
Labels: documentation, size/S

#1344 Add username and password docs to DB Secret Connection resource
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/XS

#1321 Add support for `disable_escaping` parameter for select DB Engines
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/M

#1347 Update to docker/distribution v2.8.0
  go.mod
  go.sum
Labels: dependencies, size/XS

#1343 Changed token argument to optional
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1348 Fix: properly detect the db plugin name on import
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/L

#1350 Add remaining changelog entries for 3.3.0
  CHANGELOG.md
Labels: size/XS

#1352 Fix nil pointer during duplicate group name creation
  CHANGELOG.md
  vault/resource_identity_group.go
  vault/resource_identity_group_test.go
  website/docs/r/identity_group.html.md
Labels: documentation, size/M

#1356 Handle the case where member_identity_ids might be nil
  vault/resource_identity_group_member_entity_ids.go
Labels: size/XS

#1358 Fix type assert panic in setCAChain()
  CHANGELOG.md
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
Labels: size/M

#1360 Properly handle the nil response on read in raft_snapshot_agent_config resource
  CHANGELOG.md
  vault/resource_raft_snapshot_agent_config.go
Labels: size/XS

#1361 Ensure all callers of readEntity() properly handle errEntityNotFound
  CHANGELOG.md
  vault/resource_identity_entity.go
  vault/resource_identity_entity_policies.go
  vault/resource_identity_group.go
  vault/resource_identity_group_policies.go
Labels: size/M

#1362 Update changelog for #1356
  CHANGELOG.md
Labels: size/XS

#1345 Add `auto_rotate_interval` to Transit Key backend
  vault/resource_transit_secret_backend_key.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/L
