Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-05, with the labels that each got.

#1429 Fix race condition on duplicate entity alias creation
  CHANGELOG.md
  go.mod
  internal/identity/entity/entity.go
  internal/identity/entity/entity_test.go
  testutil/testutil.go
  vault/resource_identity_entity.go
  vault/resource_identity_entity_alias.go
  vault/resource_identity_entity_alias_test.go
  vault/resource_identity_entity_policies.go
  vault/resource_identity_entity_policies_test.go
  vault/resource_identity_entity_test.go
Labels: dependencies, size/XL

#781 Add user_path and permissions_boundary_arn arguments to aws_secret_backend_role
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/XL

#1433 Update go-getter to v1.5.11
  go.mod
  go.sum
Labels: dependencies, size/XS

#1390 Improve generic secrets data doc
  website/docs/d/generic_secret.html.md
Labels: documentation, size/XS

#1378 support ldap userfilter attribute
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: enhancement, documentation, size/XS

#1438 Ignore mongodb-atlas private_key on read
  CHANGELOG.md
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/S

#1432 Force new root CA resource creation on out of band changes
  CHANGELOG.md
  util/util.go
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: documentation, size/XL

#1439 Allow `description` to be updated for `vault_auth_backend` resource
  CHANGELOG.md
  vault/auth_mount.go
  vault/resource_auth_backend.go
  vault/resource_auth_backend_test.go
  vault/structures.go
Labels: size/M

#1441 Add `allowed_serial_numbers` support (Forked #1119)
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/S

#1440 Properly force a new resource whenenver the cert is near expiry
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
Labels: size/XL

#1443 The PKI role key_usage value should be computed
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
Labels: size/L

#1418 changes to prep for releases-api migration
  .github/workflows/release.yml
  .goreleaser.yml
  .release/release-metadata.hcl
Labels: size/XS, do-not-merge

#1444 Bump terraform-plugin-sdk to v2.16.0
  go.mod
  go.sum
  vault/resource_identity_entity_test.go
Labels: dependencies, size/L

#1446 PKI: extend revocation support
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_intermediate_set_signed.go
  vault/resource_pki_secret_backend_intermediate_set_signed_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  vault/resource_pki_secret_backend_sign.go
  website/docs/r/pki_secret_backend_cert.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: documentation, size/XL

#1447 Fix TTL handling in PKI role
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/L

#1448 Properly handle nil member_entity_ids in response.
  vault/resource_identity_group_member_entity_ids.go
Labels: size/XS

#1452 Docs: add complete example for pki_secret_backend_intermediate_set_signed
  website/docs/r/pki_secret_backend_intermediate_set_signed.html.md
Labels: documentation, size/S

#1451 Add support for importing PKI config URLs
  vault/resource_pki_secret_backend_config_urls.go
  vault/resource_pki_secret_backend_config_urls_test.go
  website/docs/r/pki_secret_backend_config_urls.html.md
Labels: documentation, size/L

#1459 Set delete_all_versions on read() for generic_secret
  vault/resource_generic_secret.go
  vault/resource_generic_secret_test.go
Labels: size/S

#1434 Remove read operation on entity alias update
  util/util.go
  util/util_test.go
  vault/resource_identity_entity_alias.go
  vault/resource_identity_entity_alias_test.go
Labels: size/L

#1346 Handle host prefix stripped token_bound_cidrs
  vault/auth_token.go
  vault/auth_token_test.go
  vault/resource_alicloud_auth_backend_role.go
  vault/resource_approle_auth_backend_role.go
  vault/resource_approle_auth_backend_role_test.go
  vault/resource_aws_auth_backend_role.go
  vault/resource_azure_auth_backend_role.go
  vault/resource_cert_auth_backend_role.go
  vault/resource_gcp_auth_backend_role.go
  vault/resource_jwt_auth_backend_role.go
  vault/resource_kubernetes_auth_backend_role.go
  vault/resource_ldap_auth_backend.go
  vault/resource_token_auth_backend_role.go
  vault/resource_token_auth_backend_role_test.go
Labels: size/XL

#1462 Update changelog for 3.6.0
  CHANGELOG.md
Labels: size/S

#1461 CI: Test against vault-enterprise 1.10.3-ent
  .circleci/config.yml
  .github/workflows/build.yml
  .go-version
  Makefile
  codegen/generate.go
  codegen/generate_test.go
  codegen/templates.go
  generated/resources/transform/template/name_test.go
  go.mod
  go.sum
  testutil/testutil.go
  vault/data_identity_oidc_openid_config_test.go
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  vault/resource_kmip_secret_backend.go
  vault/resource_kmip_secret_backend_test.go
  vault/resource_kmip_secret_role_test.go
  vault/resource_kmip_secret_scope_test.go
  vault/resource_quota_lease_count_test.go
  vault/resource_raft_autopilot_test.go
  vault/resource_raft_snapshot_agent_config_test.go
Labels: dependencies, size/XL

#1466 Update opencontainers/runc to v1.1.2
  go.mod
  go.sum
Labels: dependencies, size/XS

#1467 Update gopkg.in/yaml.v3 to v3.0.0
  go.mod
  go.sum
Labels: dependencies, size/XS

#1475 Add custom health-cmd for the vault container
  .github/workflows/build.yml
Labels: size/XS
