Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-08, with the labels that each got.

#1534 Add Azure example to the doc
  website/docs/r/raft_snapshot_agent_config.html.md
Labels: documentation, size/XS

#1557 Make password_policy conflict with the formatter field
  testutil/testutil.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_backend_test.go
  website/docs/r/ad_secret_backend.html.md
Labels: documentation, size/L

#1558 Update all transform resources with namespace support
  generated/datasources/transform/decode/role_name_test.go
  generated/datasources/transform/encode/role_name_test.go
  generated/resources/transform/alphabet/name_test.go
  generated/resources/transform/role/name_test.go
  generated/resources/transform/template/name_test.go
  generated/resources/transform/transformation/name_test.go
  generated/terraform_registry.go
  main.go
  vault/provider.go
Labels: bug, size/XL

#1559 Give test ProviderFactories a try.
  internal/provider/meta.go
  internal/provider/meta_test.go
  vault/provider_test.go
  vault/resource_pki_secret_backend_root_cert_test.go
Labels: size/M

#1561 Document namespaced resource import
  website/docs/index.html.markdown
Labels: documentation, size/S

#1511 Fix typo in pkiSecretBackendRootCertResource
  vault/resource_pki_secret_backend_root_cert.go
Labels: size/XS

#1464 Add more visible note that `vault_aws_access_credentials` cannot be renewed
  website/docs/d/aws_access_credentials.html.md
Labels: documentation, size/XS

#1564 Update changelog for v3.8.1
  CHANGELOG.md
Labels: size/XS

#1556 Add test case for Consul ACL bootstrapping
  .github/workflows/build.yml
  go.mod
  go.sum
  vault/import_consul_secret_backend_test.go
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_consul_secret_backend_test.go
Labels: dependencies, size/XL

#1568 Update jira sync
  .github/workflows/jira.yaml
Labels: size/XS

#1570 fix: remove unnecessary nesting of secret data for KV-V1 secrets
  vault/resource_kv_secret.go
  vault/resource_kv_secret_test.go
Labels: size/M

#1574 Update kvv1 test to use AssertVaultState()
  testutil/testutil.go
  vault/data_source_kv_secret.go
  vault/resource_kv_secret_test.go
Labels: size/M

#1576 Fix/add kv data map
  vault/data_source_kv_secret.go
  vault/data_source_kv_secret_test.go
  vault/data_source_kv_secret_v2.go
  vault/data_source_kv_secret_v2_test.go
  vault/data_source_kv_subkeys_v2.go
  vault/data_source_kv_subkeys_v2_test.go
  website/docs/d/kv_secret.html.md
  website/docs/d/kv_secret_v2.html.md
  website/docs/d/kv_subkeys_v2.html.md
Labels: documentation, size/M

#1578 Only initialize the testProvider for acceptance tests
  Makefile
  testutil/testutil.go
  vault/provider_test.go
Labels: size/XS

#1577 Add `data` field to KV data sources
  vault/data_source_kv_secret.go
  vault/data_source_kv_secret_test.go
  vault/data_source_kv_secret_v2.go
  vault/data_source_kv_secret_v2_test.go
  vault/data_source_kv_subkeys_v2.go
  vault/data_source_kv_subkeys_v2_test.go
  website/docs/d/kv_secret.html.md
  website/docs/d/kv_secret_v2.html.md
  website/docs/d/kv_subkeys_v2.html.md
  website/docs/r/kv_secret.html.md
  website/docs/r/kv_secret_v2.html.md
Labels: documentation, size/M

#1571 Add bootstrap field to Consul backend resources
  vault/resource_consul_secret_backend.go
  vault/resource_consul_secret_backend_test.go
  website/docs/r/consul_secret_backend.html.md
Labels: documentation, size/M

#1580 Changelog for v3.8.2
  CHANGELOG.md
Labels: size/XS

#1508 Add Managed Keys support to TFVP
  internal/consts/consts.go
  vault/provider.go
  vault/resource_kv_secret_v2_test.go
  vault/resource_managed_keys.go
  vault/resource_managed_keys_test.go
  vault/resource_mount.go
  vault/resource_mount_test.go
  vault/resource_pki_secret_backend_config_ca.go
  vault/resource_pki_secret_backend_config_ca_test.go
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  website/docs/r/database_secrets_mount.md
  website/docs/r/managed_keys.html.md
  website/docs/r/mount.html.md
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/vault.erb
Labels: documentation, size/XL

#1573 Support creating Azure secret backend role by specifying the role_id
  vault/resource_azure_secret_backend_role.go
  vault/resource_azure_secret_backend_role_test.go
Labels: size/M

#1583 Additional changes like those in #1305/#1479
  vault/resource_azure_auth_backend_config.go
Labels: size/XS

#1426 Add support to perform semantic version comparisons against Vault's server version
  internal/consts/consts.go
  internal/semver/semver.go
  internal/semver/semver_test.go
  vault/provider.go
  vault/resource_aws_secret_backend.go
  vault/resource_aws_secret_backend_test.go
  vault/resource_kubernetes_secret_backend.go
  vault/resource_kubernetes_secret_backend_role.go
  vault/resource_managed_keys.go
Labels: size/XL
