Repository hashicorp/terraform-provider-vault, pull requests merged in 2022-01, with the labels that each got.

#1281 Require github.com/opencontainers/runc v1.0.3
  go.mod
  go.sum
Labels: dependencies, size/XS

#1278 Allow ed25519 on the PKI backend also for intermediate_cert_request
  vault/resource_pki_secret_backend_intermediate_cert_request.go
Labels: size/XS

#1279 [VAULT-2533] Add Redshift support to Provider
  CHANGELOG.md
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/M, feature-parity

#1282 Update changelog for #1278
  CHANGELOG.md
Labels: size/XS

#1277 Arg removal not properly applied for aws_secret_backend_role
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
Labels: size/S

#1285 Update vhosts syntax
  website/docs/r/rabbitmq_secret_backend_role.html.md
Labels: documentation, size/XS

#1284 Move TestCheckResourceAttrJSON to testutil
  testutil/testutil.go
  util/util.go
  vault/resource_aws_secret_backend_role_test.go
Labels: size/M

#1283 Update changelog for #1277
  CHANGELOG.md
Labels: size/XS

#1287 Update to containerd v1.5.9
  go.mod
  go.sum
Labels: dependencies, size/XS

#1246 r/rabbitmq_secret_backend_role - add support for `vhost_topics`
  vault/resource_rabbitmq_secret_backend_role.go
  vault/resource_rabbitmq_secret_backend_role_test.go
  website/docs/r/rabbitmq_secret_backend_role.html.md
Labels: documentation, size/XL, feature-parity

#1290 Update `CHANGELOG.md` with #1246 changes
  CHANGELOG.md
Labels: size/XS

#1291 Rename rabbitmq to rabbitMQ to follow Go naming conventions
  vault/provider.go
  vault/resource_rabbitmq_secret_backend.go
  vault/resource_rabbitmq_secret_backend_role.go
  vault/resource_rabbitmq_secret_backend_role_test.go
  vault/resource_rabbitmq_secret_backend_test.go
Labels: size/L

#1294 Factor out token field constants
  vault/auth_token.go
Labels: size/L

#1275 r/database_secret_backend_connection- add support for Couchbase db plugin
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/L, feature-parity

#1297 Add audit non HMAC'd request/response keys to mount resource
  CHANGELOG.md
  vault/resource_mount.go
  vault/resource_mount_test.go
  website/docs/r/mount.html.md
Labels: documentation, size/L

#1296 Add organization_id field to github_auth_backend (vault-1.10+)
  .circleci/config.yml
  go.mod
  go.sum
  testutil/testutil.go
  util/util.go
  util/util_test.go
  vault/auth_token.go
  vault/resource_github_auth_backend.go
  vault/resource_github_auth_backend_test.go
  website/docs/r/github_auth_backend.html.md
Labels: documentation, dependencies, size/L

#1292 r/aws_secret_backend - add support for `username_template`
  vault/resource_aws_secret_backend.go
  vault/resource_aws_secret_backend_test.go
  website/docs/r/aws_secret_backend.html.md
Labels: documentation, size/M

#1302 Update `CHANGELOG.md` after merging #1292
  CHANGELOG.md
Labels: size/XS

#1301 Adds missing nil check on crl read
  vault/resource_pki_secret_backend_crl_config.go
Labels: size/XS

#1307 Make audit_non_hmac fields computed.
  vault/resource_mount.go
Labels: size/XS

#1308 Bump the Go version to 1.17.5 for release.
  .circleci/config.yml
  .go-version
Labels: size/XS

#1312 Add nil check to resolve panic when reading RabbitMQ role from Vault
  CHANGELOG.md
  vault/resource_rabbitmq_secret_backend_role.go
Labels: size/XS

#1315 Ensure `disable_iss_validation` is honored
  CHANGELOG.md
  vault/resource_kubernetes_auth_backend_config.go
  vault/resource_kubernetes_auth_backend_config_test.go
Labels: size/S

#1298 Add KMIP secret backend resource
  CHANGELOG.md
  vault/provider.go
  vault/resource_kmip_secret_backend.go
  vault/resource_kmip_secret_backend_test.go
  vault/validators.go
  vault/validators_test.go
  website/docs/r/kmip_secret_backend.html.md
  website/vault.erb
Labels: documentation, size/XL, feature-parity

#1316 add allowed_policies_glob and disallowed_polices_glob to auth token role backend
  vault/resource_token_auth_backend_role.go
  vault/resource_token_auth_backend_role_test.go
  website/docs/r/token_auth_backend_role.html.md
Labels: documentation, size/M, feature-parity

#1323 Git ignore scratch directory
  .gitignore
Labels: size/XS

#1324 Update changelog for #1316
  CHANGELOG.md
Labels: size/XS

#1326 Use dbEngine instances in place of constants.
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/XL

#1320 Add support for configuring a DB secret's plugin_name
  CHANGELOG.md
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/XL

#1325 Add missing read handler for Redshift DB
  CHANGELOG.md
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/S
