Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-01, with the labels that each got.

#1705 raft autopilot updates
  internal/consts/consts.go
  vault/data_source_raft_autopilot_state.go
  vault/data_source_raft_autopilot_state_test.go
  vault/provider.go
  vault/resource_raft_autopilot.go
  vault/resource_raft_autopilot_test.go
  website/docs/d/raft_autopilot_state.html.md
  website/docs/r/raft_autopilot.html.md
Labels: documentation, size/XL

#1710 Add support for importing the PKI CRL config
  .github/workflows/build.yml
  .github/workflows/issue-opened.yml
  .gitignore
  .go-version
  README.md
  generated/resources/transform/role/name.go
  go.mod
  testutil/testutil.go
  testutil/testutil_test.go
  util/util.go
  vault/resource_pki_secret_backend_crl_config.go
  vault/resource_pki_secret_backend_crl_config_test.go
  website/docs/r/pki_secret_backend_crl_config.html.md
Labels: documentation, dependencies, size/XL

#1687 Add support for a KV V2 Secret Metadata resource
  internal/consts/consts.go
  vault/resource_kv_secret_v2.go
  vault/resource_kv_secret_v2_test.go
  website/docs/r/kv_secret_backend_v2.html.md
  website/docs/r/kv_secret_v2.html.md
Labels: documentation, size/L

#1713 Set ForceNew on the path field of namespaces
  vault/resource_namespace.go
  vault/resource_namespace_test.go
Labels: size/XS, resource, namespace-enhancement

#1716 Update changelog for v3.12.0 release
  CHANGELOG.md
Labels: size/XS

#1721 Add enterprise check for new Raft Autopilot parameter
  internal/provider/meta.go
  internal/provider/meta_test.go
  vault/resource_raft_autopilot.go
  vault/resource_raft_autopilot_test.go
  website/docs/r/raft_autopilot.html.md
Labels: documentation, size/L

#1735 Refactor test case for deprecated `use_microsoft_graph_api` field
  vault/resource_azure_secret_backend_test.go
Labels: size/L

#1724 Add aws auth backend config identity
  go.mod
  internal/consts/consts.go
  vault/provider.go
  vault/resource_aws_auth_backend_config_identity.go
  vault/resource_aws_auth_backend_config_identity_test.go
  website/docs/r/aws_auth_backend_config_identity.html.md
  website/vault.erb
Labels: documentation, dependencies, size/XL

#1738 add debug setup
  Makefile
  README.md
  main.go
Labels: size/M
