Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-11, with the labels that each got.

#2072 Update `CHANGELOG.md` for v3.22.0 release
  CHANGELOG.md
Labels: size/XS

#2073 fix typo in changelog header
  CHANGELOG.md
Labels: size/XS

#2077 Allow workflow_dispatch to manually run builds
  .github/workflows/build.yml
Labels: size/XS

#2049 Add support for lazily authenticating to Vault
  internal/provider/meta.go
  internal/provider/meta_test.go
  vault/data_source_kv_secret_v2_test.go
  vault/provider_test.go
  vault/resource_approle_auth_backend_role_secret_id_test.go
  vault/resource_audit_request_header_test.go
  vault/resource_auth_backend_test.go
  vault/resource_azure_auth_backend_config_test.go
  vault/resource_database_secret_backend_connection_test.go
  vault/resource_database_secrets_mount_test.go
  vault/resource_gcp_secret_impersonated_account_test.go
  vault/resource_generic_secret_test.go
  vault/resource_identity_entity_alias_test.go
  vault/resource_identity_oidc_test.go
  vault/resource_kubernetes_auth_backend_config_test.go
  vault/resource_kv_secret_v2_test.go
  vault/resource_ldap_secret_backend_test.go
  vault/resource_managed_keys_test.go
  vault/resource_mfa_totp_test.go
  vault/resource_mount_test.go
  vault/resource_namespace_test.go
  vault/resource_okta_auth_backend_group_test.go
  vault/resource_okta_auth_backend_test.go
  vault/resource_okta_auth_backend_user_test.go
  vault/resource_pki_secret_backend_cert_test.go
  vault/resource_pki_secret_backend_config_urls_test.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_sign_test.go
  vault/resource_quota_lease_count_test.go
  vault/resource_quota_rate_limit_test.go
  vault/resource_token_auth_backend_role_test.go
Labels: size/L

#2088 Prepare for v3.23.0 release
  CHANGELOG.md
Labels: size/XS

#2097 [Phase 2] Include Auth Login blocks in multiplexed Provider configuration
  go.mod
  internal/framework/validators/README.md
  internal/framework/validators/gcp.go
  internal/framework/validators/gcp_test.go
  internal/framework/validators/test-fixtures/fake_account.json
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_azure.go
  internal/provider/auth_cert.go
  internal/provider/auth_gcp.go
  internal/provider/auth_jwt.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_oci.go
  internal/provider/auth_oidc.go
  internal/provider/auth_radius.go
  internal/provider/auth_token_file.go
  internal/provider/auth_token_file_test.go
  internal/provider/auth_userpass.go
  internal/provider/fwprovider/auth_aws.go
  internal/provider/fwprovider/auth_azure.go
  internal/provider/fwprovider/auth_cert.go
  internal/provider/fwprovider/auth_gcp.go
  internal/provider/fwprovider/auth_generic.go
  internal/provider/fwprovider/auth_jwt.go
  internal/provider/fwprovider/auth_kerberos.go
  internal/provider/fwprovider/auth_oci.go
  internal/provider/fwprovider/auth_oidc.go
  internal/provider/fwprovider/auth_radius.go
  internal/provider/fwprovider/auth_userpass.go
  internal/provider/fwprovider/provider.go
  internal/sys/password_policy.go
  vault/provider.go
Labels: dependencies, size/XL
