Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-10, with the labels that each got.

#2035 build: test against Vault 1.15
  .github/workflows/build.yml
Labels: size/XS

#2008 auth/approle: set sensitive for secret values
  CHANGELOG.md
  vault/resource_approle_auth_backend_login.go
Labels: size/XS

#2012 Bring the Vault provider to gcp sql parity with Vault
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
  vault/resource_database_secrets_mount.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/L

#2034 Add support for HMAC type to vault_transit_secret_backend_key
  CHANGELOG.md
  vault/resource_transit_secret_backend_key.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/L

#2036 secret/pki: fix key_usage panic and unset function
  CHANGELOG.md
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/M

#2041 secret/transit: use ProviderFactories in test
  vault/resource_transit_secret_backend_key_test.go
Labels: size/XS

#2039 secret/kvv2: fix drift detection when disable_read is enabled
  CHANGELOG.md
  internal/consts/consts.go
  vault/resource_kv_secret_v2.go
  vault/resource_kv_secret_v2_test.go
Labels: size/M

#2037 Add state migrator in secrets/auth mounts for `disable_remount` parameter
  CHANGELOG.md
  internal/provider/schema_util.go
  internal/provider/schema_util_test.go
  vault/resource_ad_secret_backend.go
  vault/resource_auth_backend.go
  vault/resource_aws_secret_backend.go
  vault/resource_azure_secret_backend.go
  vault/resource_consul_secret_backend.go
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_secret_backend.go
  vault/resource_github_auth_backend.go
  vault/resource_jwt_auth_backend.go
  vault/resource_kmip_secret_backend.go
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_secret_backend.go
  vault/resource_nomad_secret_backend.go
  vault/resource_okta_auth_backend.go
  vault/resource_rabbitmq_secret_backend.go
  vault/resource_terraform_cloud_secret_backend.go
Labels: size/M

#2044 remove logging of password key
  vault/resource_database_secret_backend_connection.go
Labels: size/XS

#2045 Update changeglog for `v3.21.0` release
  CHANGELOG.md
Labels: size/XS

#2046 Downgrade `vault-plugin-auth-jwt` dependency to `v0.17.0`
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependencies, size/XS

#2048 fix(oidc_client): omit client_secret when client_type == "public"
  CHANGELOG.md
  vault/data_identity_oidc_client_creds.go
  vault/data_identity_oidc_client_creds_test.go
  website/docs/d/identity_oidc_client_creds.html.md
Labels: documentation, size/S

#2052 Fix failing data oidc client creds test
  vault/data_identity_oidc_client_creds_test.go
Labels: size/S

#2042 chore: update aws sdk dependency
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependencies, size/XS

#2033 Add custom metadata support to namespace resource
  CHANGELOG.md
  vault/resource_namespace.go
  vault/resource_namespace_test.go
  website/docs/r/namespace.html.md
Labels: documentation, size/M

#2050 chore: update azure sdk deps
  .go-version
  CHANGELOG.md
  go.mod
  go.sum
  vault/data_source_azure_access_credentials.go
  vault/data_source_azure_access_credentials_test.go
Labels: dependencies, size/XL

#2054 chore: fix flaky test TestReadEntity
  vault/resource_identity_entity_test.go
Labels: size/XS

#2058 workflows: don't build for changelog/docs only PRs
  .github/workflows/build.yml
  .github/workflows/go-checks.yaml
Labels: size/XS

#2063 secrets/azure: fix role update error
  CHANGELOG.md
  vault/resource_azure_secret_backend_role.go
  vault/resource_azure_secret_backend_role_test.go
Labels: size/M

#2064 GCP Auth: Modifying incorrect audience string for GCE
  CHANGELOG.md
  internal/provider/auth_gcp.go
Labels: size/XS

#2066 Support authenticating to the root namespace from within an auth_login*
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_aws_test.go
  internal/provider/auth_azure.go
  internal/provider/auth_azure_test.go
  internal/provider/auth_cert.go
  internal/provider/auth_cert_test.go
  internal/provider/auth_gcp.go
  internal/provider/auth_generic.go
  internal/provider/auth_generic_test.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_kerberos_test.go
  internal/provider/auth_oci.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_oidc.go
  internal/provider/auth_oidc_test.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  internal/provider/auth_token_file.go
  internal/provider/auth_token_file_test.go
  internal/provider/auth_userpass.go
  internal/provider/auth_userpass_test.go
  internal/provider/meta.go
  website/docs/index.html.markdown
Labels: documentation, size/XL

#2068 chore: move generated resources to vault package
  generated/datasources/transform/decode/role_name_test.go
  generated/datasources/transform/encode/role_name_test.go
  generated/resources/transform/alphabet/name_test.go
  generated/resources/transform/role/name_test.go
  generated/resources/transform/template/name_test.go
  generated/terraform_registry.go
  main.go
  vault/data_source_transform_decode.go
  vault/data_source_transform_decode_test.go
  vault/data_source_transform_encode.go
  vault/data_source_transform_encode_test.go
  vault/provider.go
  vault/resource_transform_alphabet.go
  vault/resource_transform_alphabet_test.go
  vault/resource_transform_role.go
  vault/resource_transform_role_test.go
  vault/resource_transform_template.go
  vault/resource_transform_template_test.go
  vault/resource_transform_transformation.go
  vault/resource_transform_transformation_test.go
  website/docs/d/transform_decode.html.md
  website/docs/d/transform_encode.html.md
Labels: documentation, size/XL

#2053 Add support for configuring SAML Auth resources
  CHANGELOG.md
  internal/consts/consts.go
  vault/provider.go
  vault/resource_saml_auth_backend.go
  vault/resource_saml_auth_backend_role.go
  vault/resource_saml_auth_backend_role_test.go
  vault/resource_saml_auth_backend_test.go
  website/docs/r/saml_auth_backend.html.md
  website/docs/r/saml_auth_backend_role.html.md
Labels: documentation, size/XL

#2070 Add field `set_namespace_from_token` to Provider configuration
  CHANGELOG.md
  internal/consts/consts.go
  internal/provider/meta.go
  internal/provider/meta_test.go
  internal/provider/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/M
