Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-06, with the labels that each got.

#1881 check version for allowed_domains_template field
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
Labels: size/M

#1841 Add back support for deriving the provider namespace from the Vault token's
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/meta.go
  internal/provider/meta_test.go
  vault/provider_test.go
  vault/resource_namespace.go
  vault/resource_namespace_test.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#1880 Add support to Import Issuers to a mount in PKI engine
  internal/consts/consts.go
  vault/resource_pki_secret_backend_intermediate_set_signed.go
  vault/resource_pki_secret_backend_intermediate_set_signed_test.go
  vault/resource_pki_secret_backend_key.go
  website/docs/r/pki_secret_backend_intermediate_set_signed.html.md
Labels: documentation, size/L

#1876 Fix DB engine password overwrite
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/XS

#1887 Add support for retrying kv-v2 secret data writes
  vault/resource_generic_secret.go
  vault/resource_kv_secret_v2.go
Labels: size/S

#1875 secrets/ldap: fix bindpass getting overwritten
  docker-compose.yaml
  vault/resource_ldap_secret_backend.go
  vault/resource_ldap_secret_backend_test.go
Labels: size/L

#1893 Update CHANGELOG.md for 3.16.0 release
  CHANGELOG.md
Labels: size/XS

#1896 Update resource name for vault_ldap_secret_library
  website/docs/r/ldap_secret_backend_library_set.html.md
Labels: documentation, size/XS

#1895 workflows: add actionlint and go-checks
  .github/workflows/actionlint.yaml
  .github/workflows/build.yml
  .github/workflows/go-checks.yaml
  .github/workflows/release.yml
Labels: size/XS

#1878 Add support for max_page_size in the vault_ldap_auth_backend
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/XS

#1906 chore: update vault build version matrix
  .github/workflows/build.yml
  website/docs/r/ldap_auth_backend.html.md
Labels: documentation, size/XS

#1902 make okta auth user groups optional
  vault/resource_okta_auth_backend.go
  vault/resource_okta_auth_backend_test.go
  website/docs/r/okta_auth_backend.html.md
  website/docs/r/okta_auth_backend_user.html.md
Labels: documentation, size/S

#1877 Add AWS Static Roles support
  internal/consts/consts.go
  internal/provider/meta.go
  vault/data_source_aws_static_credentials.go
  vault/data_source_aws_static_credentials_test.go
  vault/provider.go
  vault/resource_aws_secret_backend_static_role.go
  vault/resource_aws_secret_backend_static_role_test.go
  website/docs/d/aws_static_credentials.md
  website/docs/r/aws_secret_backend_static_role.md
  website/vault.erb
Labels: documentation, size/XL

#1897 Add extra bits to aid in migration to multi-issuer functionality
  internal/consts/consts.go
  vault/data_source_pki_secret_backend_issuer.go
  vault/data_source_pki_secret_backend_issuer_test.go
  vault/data_source_pki_secret_backend_issuers.go
  vault/data_source_pki_secret_backend_issuers_test.go
  vault/data_source_pki_secret_backend_key.go
  vault/data_source_pki_secret_backend_key_test.go
  vault/data_source_pki_secret_backend_keys.go
  vault/data_source_pki_secret_backend_keys_test.go
  vault/provider.go
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_issuer.go
  vault/resource_pki_secret_backend_issuer_test.go
  vault/resource_pki_secret_backend_key.go
  vault/resource_pki_secret_backend_key_test.go
  vault/resource_pki_secret_backend_root_cert.go
  website/docs/d/pki_secret_backend_issuer.html.md
  website/docs/d/pki_secret_backend_issuers.html.md
  website/docs/d/pki_secret_backend_key.html.md
  website/docs/d/pki_secret_backend_keys.html.md
  website/docs/r/pki_secret_backend_issuer.html.md
  website/docs/r/pki_secret_backend_key.html.md
  website/vault.erb
Labels: documentation, size/XL

#1910 Add support for multi-issuer functionality to PKI
  internal/consts/consts.go
  vault/data_source_pki_secret_backend_issuer.go
  vault/data_source_pki_secret_backend_issuer_test.go
  vault/data_source_pki_secret_backend_issuers.go
  vault/data_source_pki_secret_backend_issuers_test.go
  vault/data_source_pki_secret_backend_key.go
  vault/data_source_pki_secret_backend_key_test.go
  vault/data_source_pki_secret_backend_keys.go
  vault/data_source_pki_secret_backend_keys_test.go
  vault/provider.go
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_config_ca.go
  vault/resource_pki_secret_backend_config_ca_test.go
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_intermediate_set_signed.go
  vault/resource_pki_secret_backend_intermediate_set_signed_test.go
  vault/resource_pki_secret_backend_issuer.go
  vault/resource_pki_secret_backend_issuer_test.go
  vault/resource_pki_secret_backend_key.go
  vault/resource_pki_secret_backend_key_test.go
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
  website/docs/d/pki_secret_backend_issuer.html.md
  website/docs/d/pki_secret_backend_issuers.html.md
  website/docs/d/pki_secret_backend_key.html.md
  website/docs/d/pki_secret_backend_keys.html.md
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
  website/docs/r/pki_secret_backend_intermediate_set_signed.html.md
  website/docs/r/pki_secret_backend_issuer.html.md
  website/docs/r/pki_secret_backend_key.html.md
  website/docs/r/pki_secret_backend_role.html.md
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
  website/vault.erb
Labels: documentation, size/XL

#1909 Ensure auth_login_cert is a valid login method
  internal/consts/consts.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_aws_test.go
  internal/provider/auth_azure.go
  internal/provider/auth_azure_test.go
  internal/provider/auth_cert.go
  internal/provider/auth_cert_test.go
  internal/provider/auth_gcp.go
  internal/provider/auth_gcp_test.go
  internal/provider/auth_generic.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_kerberos_test.go
  internal/provider/auth_oci.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_oidc.go
  internal/provider/auth_oidc_test.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  internal/provider/auth_userpass.go
  vault/provider_test.go
Labels: size/XL

#1913 Harmonize all auth_login Init() tests
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_aws_test.go
  internal/provider/auth_azure.go
  internal/provider/auth_azure_test.go
  internal/provider/auth_cert_test.go
  internal/provider/auth_gcp_test.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_kerberos_test.go
  internal/provider/auth_oci.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_oidc.go
  internal/provider/auth_oidc_test.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  internal/provider/auth_userpass.go
  internal/provider/auth_userpass_test.go
Labels: size/XL

#1912 don't send password updates if no change
  docker-compose.yaml
  testdata/cassandra.yaml
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/XL

#1901 Add x509 support to TFVP
  internal/consts/consts.go
  vault/resource_database_secret_backend_role.go
  vault/resource_database_secret_backend_role_test.go
  website/docs/r/database_secret_backend_role.md
Labels: documentation, size/XL

#1915 Merge `release/vault-next` into `main`
  .github/workflows/build.yml
  internal/consts/consts.go
  internal/provider/meta.go
  vault/data_source_aws_static_credentials.go
  vault/data_source_aws_static_credentials_test.go
  vault/provider.go
  vault/resource_aws_secret_backend_static_role.go
  vault/resource_aws_secret_backend_static_role_test.go
  website/docs/d/aws_static_credentials.md
  website/docs/r/aws_secret_backend_static_role.md
  website/vault.erb
Labels: documentation, size/XL

#1914 Updates changelog for v3.17.0 release
  CHANGELOG.md
Labels: size/XS
