Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-08, with the labels that each got.

#1966 Update changelog for 3.19.0 release
  CHANGELOG.md
Labels: size/XS

#1958 Update `resource_azure_secret_backend_role` to include `permanently_delete` arg
  vault/resource_azure_secret_backend_role.go
  vault/resource_azure_secret_backend_role_test.go
  website/docs/r/azure_secret_backend_role.html.md
Labels: documentation, size/M

#1957 update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S

#1963 Add `use_sts_region_from_client` to AWS Auth Config
  CHANGELOG.md
  internal/consts/consts.go
  internal/provider/meta.go
  vault/resource_aws_auth_backend_client.go
  vault/resource_aws_auth_backend_client_test.go
  website/docs/r/aws_auth_backend_client.html.md
Labels: documentation, size/M

#1978 Fixes panic when lookup-self returns nil token info
  CHANGELOG.md
  internal/provider/meta.go
Labels: size/XS

#1981 Update pki_secret_backend_role.html.md
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/XS

#1984 Update aws_auth_backend_role.html.md
  website/docs/r/aws_auth_backend_role.html.md
Labels: documentation, size/XS

#1980 Add accessor computed attribute for gcp auth backend
  CHANGELOG.md
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_auth_backend_test.go
  website/docs/r/gcp_auth_backend.html.md
Labels: documentation, size/XS

#1985 Rework issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/00_bug_report.yml
  .github/ISSUE_TEMPLATE/01_documentation.yml
  .github/ISSUE_TEMPLATE/02_enhancement.yml
  .github/ISSUE_TEMPLATE/03_new_resource.yml
  .github/ISSUE_TEMPLATE/04_other.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: size/XL

#1989 fix bug template rendering
  .github/ISSUE_TEMPLATE/00_bug_report.yml
Labels: size/XS

#1988 docs: CHANGELOG entry for PR #1958
  CHANGELOG.md
Labels: size/XS

#1973 Resolve TF state for PKI Multi-Issuer workflows
  go.mod
  util/util.go
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_issuer.go
  vault/resource_pki_secret_backend_key_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
Labels: dependencies, size/XL

#1996 Prepare for v3.20.0
  CHANGELOG.md
Labels: size/XS

#1994 Add support for roles to both rate limit and lease count quotas
  vault/resource_quota_lease_count.go
  vault/resource_quota_lease_count_test.go
  vault/resource_quota_rate_limit.go
  vault/resource_quota_rate_limit_test.go
  website/docs/r/quota_lease_count.md
  website/docs/r/quota_rate_limit.md
Labels: documentation, size/L
