Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-12, with the labels that each got.

#2104 kvv2: make path/mount regex lazy eval
  CHANGELOG.md
  vault/resource_kv_secret_v2.go
  vault/resource_kv_secret_v2_test.go
Labels: size/S

#2105 docs: fix database_secret_backend_role formatting
  website/docs/r/database_secret_backend_role.md
Labels: documentation, size/S

#2108 fix: 2107: Add missing schema fields and tests for ext_key_usage_oids
  CHANGELOG.md
  internal/consts/consts.go
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/XS

#2090 [Phase 2] Complete the provider configuration setup
  go.mod
  internal/consts/consts.go
  internal/framework/base/base.go
  internal/framework/client/client.go
  internal/framework/validators/README.md
  internal/framework/validators/file_exists.go
  internal/framework/validators/file_exists_test.go
  internal/framework/validators/gcp.go
  internal/framework/validators/gcp_test.go
  internal/framework/validators/kerberos.go
  internal/framework/validators/kerberos_test.go
  internal/framework/validators/path.go
  internal/framework/validators/path_test.go
  internal/framework/validators/testdata/fake_account.json
  internal/framework/validators/uri.go
  internal/framework/validators/uri_test.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_azure.go
  internal/provider/auth_cert.go
  internal/provider/auth_gcp.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_oci.go
  internal/provider/auth_oidc.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  internal/provider/auth_token_file.go
  internal/provider/auth_token_file_test.go
  internal/provider/auth_userpass.go
  internal/provider/fwprovider/auth.go
  internal/provider/fwprovider/auth_aws.go
  internal/provider/fwprovider/auth_azure.go
  internal/provider/fwprovider/auth_cert.go
  internal/provider/fwprovider/auth_gcp.go
  internal/provider/fwprovider/auth_generic.go
  internal/provider/fwprovider/auth_jwt.go
  internal/provider/fwprovider/auth_kerberos.go
  internal/provider/fwprovider/auth_oci.go
  internal/provider/fwprovider/auth_oidc.go
  internal/provider/fwprovider/auth_radius.go
  internal/provider/fwprovider/auth_token_file.go
  internal/provider/fwprovider/auth_userpass.go
  internal/provider/fwprovider/provider.go
  internal/provider/meta.go
  internal/provider/meta_test.go
  internal/provider/provider.go
  internal/provider/validators.go
  internal/sys/password_policy.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#2067 [Phase 1] Multiplex provider - minimal TF Plugin Framework provider implementation
  go.mod
  go.sum
  internal/consts/consts.go
  internal/framework/base/base.go
  internal/framework/client/client.go
  internal/framework/validators/README.md
  internal/framework/validators/file_exists.go
  internal/framework/validators/file_exists_test.go
  internal/framework/validators/gcp.go
  internal/framework/validators/gcp_test.go
  internal/framework/validators/kerberos.go
  internal/framework/validators/kerberos_test.go
  internal/framework/validators/path.go
  internal/framework/validators/path_test.go
  internal/framework/validators/testdata/fake_account.json
  internal/framework/validators/uri.go
  internal/framework/validators/uri_test.go
  internal/provider/auth.go
  internal/provider/auth_aws.go
  internal/provider/auth_azure.go
  internal/provider/auth_cert.go
  internal/provider/auth_gcp.go
  internal/provider/auth_jwt.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos.go
  internal/provider/auth_oci.go
  internal/provider/auth_oidc.go
  internal/provider/auth_radius.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  internal/provider/auth_token_file.go
  internal/provider/auth_token_file_test.go
  internal/provider/auth_userpass.go
  internal/provider/fwprovider/auth.go
  internal/provider/fwprovider/auth_aws.go
  internal/provider/fwprovider/auth_azure.go
  internal/provider/fwprovider/auth_cert.go
  internal/provider/fwprovider/auth_gcp.go
  internal/provider/fwprovider/auth_generic.go
  internal/provider/fwprovider/auth_jwt.go
  internal/provider/fwprovider/auth_kerberos.go
  internal/provider/fwprovider/auth_oci.go
  internal/provider/fwprovider/auth_oidc.go
  internal/provider/fwprovider/auth_radius.go
  internal/provider/fwprovider/auth_token_file.go
  internal/provider/fwprovider/auth_userpass.go
  internal/provider/fwprovider/provider.go
  internal/provider/meta.go
  internal/provider/meta_test.go
  internal/provider/provider.go
  internal/provider/validators.go
  internal/sys/password_policy.go
  main.go
  schema/provider.go
  vault/provider_factory.go
  vault/provider_test.go
  website/docs/index.html.markdown
Labels: documentation, dependencies, size/XL

#2040 Fix tests with Vault Community Edition
  .github/workflows/build.yml
  testutil/testutil.go
  vault/resource_gcp_auth_backend_test.go
  vault/resource_github_auth_backend_test.go
  vault/resource_jwt_auth_backend_test.go
  vault/resource_mount_test.go
  vault/resource_pki_secret_backend_crl_config_test.go
Labels: size/S

#1997 Add tune block support to gcp auth backend and relocate auth mount test functions
  CHANGELOG.md
  testutil/testutil.go
  vault/resource_auth_backend_test.go
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_auth_backend_test.go
  vault/resource_github_auth_backend_test.go
  website/docs/r/gcp_auth_backend.html.md
Labels: documentation, size/XL

#2110 Fixes failing tests for `make test` run in build step
  CHANGELOG.md
  vault/resource_auth_backend_test.go
  vault/resource_gcp_auth_backend_test.go
  vault/resource_github_auth_backend_test.go
Labels: size/S

#2114 auth/k8s: update the description for token_reviewer_jwt
  vault/resource_kubernetes_auth_backend_config.go
  website/docs/r/kubernetes_auth_backend_config.md
Labels: documentation, size/XS

#2113 Add acceptance tests for the password policy framework implementation
  internal/framework/base/base.go
  internal/provider/fwprovider/provider.go
  internal/providertest/providertest.go
  internal/vault/auth/README.md
  internal/vault/secrets/README.md
  internal/vault/sys/README.md
  internal/vault/sys/password_policy.go
  internal/vault/sys/password_policy_test.go
  vault/password_policy.go
  vault/provider.go
  vault/resource_password_policy.go
  vault/resource_password_policy_test.go
Labels: size/XL

#2116 Refactor base package for more reusability
  internal/framework/base/base.go
  internal/framework/base/schema.go
  internal/framework/model/model.go
  internal/provider/fwprovider/provider.go
  internal/vault/sys/password_policy.go
  internal/vault/sys/password_policy_test.go
  testutil/testutil.go
Labels: size/XL

#2118 normalize resource model name across CRUD operations
  internal/vault/sys/password_policy.go
Labels: size/M
