Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-09, with the labels that each got.

#2003 docs: add schema field to ldap secrets
  website/docs/r/ldap_secret_backend.html.md
Labels: documentation, size/XS

#1140 Add allowed_email_sans field to write and update functions of vault_cert_auth_backend_role
  vault/resource_cert_auth_backend_role.go
Labels: size/XS

#2007 fix lint build error
  vault/resource_cert_auth_backend_role.go
Labels: size/XS

#2001 docs: mark allowed_names as deprected
  website/docs/r/cert_auth_backend_role.html.md
Labels: documentation, size/XS

#2005 Update k8s-auth config to support unsetting the K8s CA Cert
  .github/workflows/build.yml
  internal/consts/consts.go
  internal/provider/meta.go
  vault/data_source_kubernetes_auth_backend_config.go
  vault/data_source_kubernetes_auth_backend_config_test.go
  vault/data_source_kubernetes_credentials_test.go
  vault/resource_kubernetes_auth_backend_config.go
  vault/resource_kubernetes_auth_backend_config_test.go
  vault/resource_kubernetes_secret_backend.go
  vault/resource_kubernetes_secret_backend_role_test.go
  vault/resource_kubernetes_secret_backend_test.go
  vault/resource_quota_rate_limit.go
Labels: size/XL

#2014 Update Changelog for v3.20.1 release
  CHANGELOG.md
Labels: size/XS

#2018 docs: fix typo in vault_mfa_duo heading
  website/docs/r/mfa_duo.html.md
Labels: documentation, size/XS

#2016 Updates the documentation and field description for the `transit_secret_backend_key/auto_rotate_period` to ensure that the unit of time being used is specified
  vault/resource_transit_secret_backend_key.go
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/XS

#2019 add not_before_duration to ssh_secret_backend_role
  CHANGELOG.md
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#2013 add local var for aws secret engine
  CHANGELOG.md
  vault/resource_aws_secret_backend.go
  vault/resource_aws_secret_backend_test.go
  website/docs/r/aws_secret_backend.html.md
Labels: documentation, size/XS

#2024 docs: nomad secret role backend is required
  website/docs/r/nomad_secret_role.html.md
Labels: documentation, size/XS

#2011 Add support for DB Adv TTL Mgmt
  docker-compose.yaml
  internal/consts/consts.go
  vault/resource_database_secret_backend_static_role.go
  vault/resource_database_secret_backend_static_role_test.go
  website/docs/r/database_secret_backend_static_role.md
Labels: documentation, size/XL

#2029 auth_login: enforce empty client token
  Makefile
  internal/provider/auth.go
  internal/provider/auth_aws_test.go
  internal/provider/auth_azure_test.go
  internal/provider/auth_cert_test.go
  internal/provider/auth_gcp_test.go
  internal/provider/auth_jwt_test.go
  internal/provider/auth_kerberos_test.go
  internal/provider/auth_oci_test.go
  internal/provider/auth_oidc_test.go
  internal/provider/auth_radius_test.go
  internal/provider/auth_test.go
  internal/provider/auth_token_file_test.go
  internal/provider/auth_userpass_test.go
  internal/provider/meta.go
Labels: size/XL

#2031 logging: prevent duplicates and incorrect levels
  CHANGELOG.md
  main.go
Labels: size/XS
