Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-05, with the labels that each got.

#1821 VAULT 15208/ldap static credential data source
  internal/consts/consts.go
  vault/data_source_ldap_static_role_credentials.go
  vault/data_source_ldap_static_role_credentials_test.go
  vault/provider.go
  vault/resource_ldap_secret_backend.go
  vault/resource_ldap_secret_backend_static_role.go
  vault/resource_ldap_secret_backend_static_role_test.go
  website/docs/d/ldap_static_role_credentials.html.md
  website/docs/r/ldap_secret_backend_static_role.html.md
  website/vault.erb
Labels: documentation, size/XL

#1832 add ldap library set resource
  .github/workflows/build.yml
  docker-compose.yaml
  internal/consts/consts.go
  vault/provider.go
  vault/resource_ldap_secret_backend_library_set.go
  vault/resource_ldap_secret_backend_library_set_test.go
  website/docs/r/ldap_secret_backend_library_set.html.md
  website/vault.erb
Labels: documentation, size/XL

#1833 ldap dynamic credential data source
  internal/consts/consts.go
  vault/data_source_ldap_dynamic_role_credentials.go
  vault/data_source_ldap_dynamic_role_credentials_test.go
  vault/data_source_ldap_static_role_credentials.go
  vault/provider.go
  vault/resource_ldap_secret_backend_dynamic_role.go
  vault/resource_ldap_secret_backend_dynamic_role_test.go
  website/docs/d/ldap_dynamic_role_credentials.html.md
  website/docs/r/ldap_secret_backend_dynamic_role.html.md
  website/vault.erb
Labels: documentation, size/XL

#1839 Update changelog for `3.15.1` release
  CHANGELOG.md
Labels: size/XS

#1840 Revert #1830
  CHANGELOG.md
  go.mod
  go.sum
  internal/consts/consts.go
  internal/provider/meta.go
  vault/provider.go
  vault/provider_test.go
Labels: dependencies, size/M

#1829 Add support for PKI Key resource
  internal/consts/consts.go
  vault/provider.go
  vault/resource_pki_secret_backend_key.go
  vault/resource_pki_secret_backend_key_test.go
  website/docs/r/pki_secret_backend_key.html.md
  website/vault.erb
Labels: documentation, size/XL

#1842 remove deprecated function oktaAuthBackendExists
  vault/resource_okta_auth_backend.go
Labels: size/XS

#1847 deprecate ad secrets resources
  vault/data_source_ad_credentials.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_library.go
  vault/resource_ad_secret_roles.go
  website/docs/d/ad_access_credentials.html.md
  website/docs/r/ad_secret_backend.html.md
  website/docs/r/ad_secret_backend_library.html.md
  website/docs/r/ad_secret_role.html.md
Labels: documentation, size/S

#1846 secrets/ldap: use Computed for fields with default values
  vault/resource_ldap_secret_backend.go
Labels: size/XS

#1845 secret/pki: add issuer_ref field
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/S

#1827 Data source vault auth backends
  internal/consts/consts.go
  vault/data_source_auth_backends.go
  vault/data_source_auth_backends_test.go
  vault/provider.go
  website/docs/d/auth_backends.html.md
Labels: documentation, size/L

#1848 pki/secrets: Update Role resource to use more up-to-date patterns
  internal/consts/consts.go
  vault/resource_pki_secret_backend_role.go
Labels: size/XL

#1858 pki/secrets: add missing fields to role resource
  internal/consts/consts.go
  vault/resource_pki_secret_backend_role.go
  vault/resource_pki_secret_backend_role_test.go
  website/docs/r/pki_secret_backend_role.html.md
Labels: documentation, size/M

#1844 Add multi-issuer support to generate root cert resource
  internal/consts/consts.go
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_config_ca.go
  vault/resource_pki_secret_backend_config_ca_test.go
  vault/resource_pki_secret_backend_intermediate_set_signed.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_sign.go
  website/docs/r/pki_secret_backend_root_cert.html.md
Labels: documentation, size/XL

#1863 update gha workflows
  .github/workflows/build.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/jira.yaml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: size/M

#1794 fix vault_jwt_auth_backend import guidance to specify "path"
  website/docs/r/jwt_auth_backend.html.md
Labels: documentation, size/XS

#1864 remove test for vault 1.10
  .github/workflows/build.yml
Labels: size/XS

#967 Added time specifications to token doc
  website/docs/r/token.html.md
Labels: documentation, size/XS

#1823 Add documentation of region for vault_aws_access_credentials
  website/docs/d/aws_access_credentials.html.md
Labels: documentation, size/XS

#1822 Update aws_access_credentials documentation link to credential_type
  website/docs/d/aws_access_credentials.html.md
Labels: documentation, size/XS

#1859 VAULT-8099 LDAP secrets engine
  .github/workflows/build.yml
  docker-compose.yaml
  internal/consts/consts.go
  testutil/testutil.go
  vault/data_source_ad_credentials.go
  vault/data_source_ldap_dynamic_role_credentials.go
  vault/data_source_ldap_dynamic_role_credentials_test.go
  vault/data_source_ldap_static_role_credentials.go
  vault/data_source_ldap_static_role_credentials_test.go
  vault/provider.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_library.go
  vault/resource_ad_secret_roles.go
  vault/resource_github_team.go
  vault/resource_ldap_secret_backend.go
  vault/resource_ldap_secret_backend_dynamic_role.go
  vault/resource_ldap_secret_backend_dynamic_role_test.go
  vault/resource_ldap_secret_backend_library_set.go
  vault/resource_ldap_secret_backend_library_set_test.go
  vault/resource_ldap_secret_backend_static_role.go
  vault/resource_ldap_secret_backend_static_role_test.go
  vault/resource_ldap_secret_backend_test.go
  website/docs/d/ad_access_credentials.html.md
  website/docs/d/ldap_dynamic_role_credentials.html.md
  website/docs/d/ldap_static_role_credentials.html.md
  website/docs/r/ad_secret_backend.html.md
  website/docs/r/ad_secret_backend_library.html.md
  website/docs/r/ad_secret_role.html.md
  website/docs/r/ldap_secret_backend.html.md
  website/docs/r/ldap_secret_backend_dynamic_role.html.md
  website/docs/r/ldap_secret_backend_library_set.html.md
  website/docs/r/ldap_secret_backend_static_role.html.md
  website/vault.erb
Labels: documentation, size/XL

#1868 deprecate consts.FieldBackend and add docs for FieldMount and FieldPath
  internal/consts/consts.go
Labels: size/XS

#1869 build: use setup-terraform action workflow
  .github/workflows/build.yml
  Makefile
Labels: size/S

#1756 Fix and update documentation of the `vault_namespace` resource
  website/docs/r/namespace.html.md
Labels: documentation, size/S

#1871 azure/auth: fix config path parsing
  vault/resource_azure_auth_backend_config.go
  vault/resource_azure_auth_backend_config_test.go
Labels: size/S

#1872 use TypeInt for DefaultTTL and MaxTTL
  vault/resource_ldap_secret_backend_dynamic_role.go
Labels: size/XS

#1873 Fix example in GCP Auth Backend Role docs
  website/docs/r/gcp_auth_backend_role.html.md
Labels: documentation, size/XS

#1676 Support allowed_domains_template on ssh_secret_backend_role. Fixes hashicorp#1675
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  website/docs/r/ssh_secret_backend_role.html.md
Labels: documentation, size/XS

#1865 Add multi-issuer support to PKI Intermediate resources
  internal/consts/consts.go
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_intermediate_cert_request.go
  vault/resource_pki_secret_backend_intermediate_cert_request_test.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
  website/docs/r/pki_secret_backend_intermediate_cert_request.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
Labels: documentation, size/XL
