Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-03, with the labels that each got.

#1787 Add nil check for `IsEnterpriseSupported` util
  internal/provider/meta.go
  internal/provider/meta_test.go
Labels: size/XS

#1781 Fix KV incorrect metadata path for prefixed mounts
  vault/resource_kv_secret_backend_v2_test.go
  vault/resource_kv_secret_v2.go
  vault/resource_kv_secret_v2_test.go
Labels: size/M

#1795 Enable Vault 1.13 in CI
  .github/workflows/build.yml
Labels: size/XS

#1796 Merge Vault 1.13 features to `main`
  vault/provider.go
  vault/resource_gcp_secret_impersonated_account.go
  vault/resource_gcp_secret_impersonated_account_test.go
  website/docs/r/gcp_secret_impersonated_account.html.md
Labels: documentation, size/XL

#1610 Add vault_audit_request_header resource
  vault/provider.go
  vault/resource_audit_request_header.go
  vault/resource_audit_request_header_test.go
  website/docs/r/audit_request_header.html.md
  website/vault.erb
Labels: documentation, size/XL

#1797 Enable GCP impersonated account test for Vault 1.13
  internal/consts/consts.go
  vault/resource_gcp_secret_impersonated_account.go
  vault/resource_gcp_secret_impersonated_account_test.go
Labels: size/S

#1798 Update changelog for 3.14.0 release
  CHANGELOG.md
Labels: size/XS

#1803 Avoid writing empty strings to Vault when creating managed keys
  testutil/testutil.go
  vault/resource_managed_keys.go
  vault/resource_managed_keys_test.go
Labels: size/M

#1750 Ensure that the qr_size can be properly configured.
  internal/identity/mfa/duo.go
  internal/identity/mfa/login_enforcement.go
  internal/identity/mfa/mfa.go
  internal/identity/mfa/okta.go
  internal/identity/mfa/ping_id.go
  internal/identity/mfa/totp.go
  util/util.go
  util/util_test.go
  vault/resource_identity_mfa_duo_test.go
  vault/resource_identity_mfa_login_enforcement_test.go
  vault/resource_identity_mfa_totp_test.go
Labels: size/XL

#1804 Vault 13682/add backend resource and test
  go.mod
  internal/consts/consts.go
  testutil/testutil.go
  vault/provider.go
  vault/resource_mongodbatlas_secret_backend.go
  vault/resource_mongodbatlas_secret_backend_test.go
  website/docs/r/mongodbatlas_secret_backend.html.md
  website/vault.erb
Labels: documentation, dependencies, size/XL
