Repository hashicorp/terraform-provider-vault, pull requests merged in 2023-02, with the labels that each got.

#1712 Add resource for new GCP impersonated account endpoints
  vault/provider.go
  vault/resource_gcp_secret_impersonated_account.go
  vault/resource_gcp_secret_impersonated_account_test.go
  website/docs/r/gcp_secret_impersonated_account.html.md
Labels: documentation, size/XL

#1744 Revert "Add resource for GCP impersonated account endpoints (#1712)"
  vault/provider.go
  vault/resource_gcp_secret_impersonated_account.go
  vault/resource_gcp_secret_impersonated_account_test.go
  website/docs/r/gcp_secret_impersonated_account.html.md
Labels: documentation, size/XL

#1737 Fix issue where removing optional fields in database secrets backend connection resource did not reset the fields to their default values
  vault/resource_database_secret_backend_connection.go
  vault/resource_database_secret_backend_connection_test.go
Labels: size/M

#1745 Add resource for GCP impersonated account endpoints
  vault/provider.go
  vault/resource_gcp_secret_impersonated_account.go
  vault/resource_gcp_secret_impersonated_account_test.go
  website/docs/r/gcp_secret_impersonated_account.html.md
Labels: documentation, size/XL

#1760 Fix KVV2 datasource upon retrieval of soft deleted secrets
  vault/data_source_kv_secret_v2.go
  vault/data_source_kv_secret_v2_test.go
Labels: size/M

#1722 Fix construction of metadata path in KV V2 resource
  vault/resource_kv_secret_v2.go
  vault/resource_kv_secret_v2_test.go
Labels: size/M

#1764 Update `CHANGELOG.md` for v3.13.0 release
  CHANGELOG.md
Labels: size/XS

#1763 set VAULT_AUTH_CONFIG_GITHUB_TOKEN on vault container to avoid GH rate limit when running acceptance tests
  .github/workflows/build.yml
Labels: size/XS
