Repository hashicorp/terraform-provider-vault, pull requests merged in 2024-04, with the labels that each got.

#1454 Add `key_type` and `key_bits` to `vault_ssh_secret_backend_ca`
  vault/resource_ssh_secret_backend_ca.go
  website/docs/r/ssh_secret_backend_ca.html.md
Labels: documentation, size/XS, feature-parity

#2221 chore: update vault test matrix
  .github/workflows/build.yml
  vault/resource_azure_secret_backend.go
  vault/resource_secrets_sync_config_test.go
Labels: size/XS

#2222 chore: improve issue template formatting
  .github/ISSUE_TEMPLATE/00_bug_report.yml
  .github/ISSUE_TEMPLATE/01_documentation.yml
  .github/ISSUE_TEMPLATE/02_enhancement.yml
  .github/ISSUE_TEMPLATE/03_new_resource.yml
  .github/ISSUE_TEMPLATE/04_other.yml
Labels: size/L

#2230 (chore): add LICENSE file to terraform provider release archives
  .goreleaser.yml
Labels: size/XS
