Repository hashicorp/terraform-provider-vault, pull requests merged in 2024-05, with the labels that each got.

#2231 add iam_tags to vault_aws_secret_backend_role
  CHANGELOG.md
  vault/resource_aws_secret_backend_role.go
  vault/resource_aws_secret_backend_role_test.go
  website/docs/r/aws_secret_backend_role.html.md
Labels: documentation, size/S

#2232 auth/jwt: return error on role delete failure
  CHANGELOG.md
  vault/resource_jwt_auth_backend_role.go
Labels: size/XS

#2159 New resources `vault_plugin` and `vault_plugin_pinned_version`
  .github/workflows/build.yml
  CHANGELOG.md
  internal/provider/provider.go
  vault/provider.go
  vault/resource_plugin.go
  vault/resource_plugin_pinned_version.go
  vault/resource_plugin_pinned_version_test.go
  vault/resource_plugin_test.go
  website/docs/r/plugin.html.md
  website/docs/r/plugin_pinned_version.html.md
  website/vault.erb
Labels: documentation, size/XL

#2133 Support inheritable resource quotas
  CHANGELOG.md
  vault/resource_quota_lease_count.go
  vault/resource_quota_lease_count_test.go
  vault/resource_quota_rate_limit.go
  vault/resource_quota_rate_limit_test.go
  website/docs/r/quota_lease_count.md
  website/docs/r/quota_rate_limit.md
Labels: documentation, size/XL

#2238 chore: bump and pin github actions
  .github/workflows/build.yml
  .github/workflows/issue-opened.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: size/XS

#2235 Add missing parameters to `vault_mount`
  internal/consts/consts.go
  vault/resource_mount.go
  vault/resource_mount_test.go
  website/docs/r/mount.html.md
Labels: size/XL
