Repository hashicorp/terraform-provider-vault, pull requests merged in 2024-03, with the labels that each got.

#2150 Add new secret sync destination fields
  internal/consts/consts.go
  vault/provider.go
  vault/resource_secrets_sync_aws_destination.go
  vault/resource_secrets_sync_aws_destination_test.go
  vault/resource_secrets_sync_azure_destination_test.go
  vault/resource_secrets_sync_gcp_destination.go
  vault/resource_secrets_sync_gcp_destination_test.go
  vault/resource_secrets_sync_gh_destination.go
  vault/resource_secrets_sync_gh_destination_test.go
  vault/resource_secrets_sync_github_apps.go
  vault/resource_secrets_sync_github_apps_test.go
  website/docs/r/secrets_sync_aws_destination.html.md
  website/docs/r/secrets_sync_gcp_destination.html.md
  website/docs/r/secrets_sync_gh_destination.html.md
  website/docs/r/secrets_sync_github_apps.html.md
  website/vault.erb
Labels: documentation, size/XL

#2175 fix build vault api version
  go.mod
  go.sum
Labels: dependencies, size/XS

#2179 remove golangci-lint
  .github/workflows/golangci-lint.yml
Labels: size/XS

#2181 Remove deprecated fields from resources and documentation ahead of v.4.0.0
  internal/identity/group/group.go
  vault/resource_ad_secret_backend.go
  vault/resource_ad_secret_backend_test.go
  vault/resource_cert_auth_backend_role.go
  vault/resource_consul_secret_backend_role.go
  vault/resource_consul_secret_backend_role_test.go
  vault/resource_identity_group_member_entity_ids.go
  vault/resource_identity_group_member_group_ids.go
  vault/resource_ldap_secret_backend.go
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_root_cert.go
  vault/resource_pki_secret_backend_root_cert_test.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
  vault/resource_pki_secret_backend_root_sign_intermediate_test.go
  vault/resource_pki_secret_backend_sign.go
  vault/resource_pki_secret_backend_sign_test.go
  vault/resource_ssh_secret_backend_role.go
  vault/resource_ssh_secret_backend_role_test.go
  vault/resource_transit_secret_backend_key.go
  vault/resource_transit_secret_backend_key_test.go
  website/docs/r/ad_secret_backend.html.md
  website/docs/r/cert_auth_backend_role.html.md
  website/docs/r/consul_secret_backend_role.html.md
  website/docs/r/identity_group_member_entity_ids.html.md
  website/docs/r/ldap_secret_backend.html.md
  website/docs/r/pki_secret_backend_root_cert.html.md
  website/docs/r/pki_secret_backend_root_sign_intermediate.html.md
  website/docs/r/pki_secret_backend_sign.html.md
  website/docs/r/ssh_secret_backend_role.html.md
  website/docs/r/transit_secret_backend_key.html.md
Labels: documentation, size/XL

#2186 Fix PKI Issuer overwrites on updates
  CHANGELOG.md
  vault/resource_pki_secret_backend_issuer.go
  vault/resource_pki_secret_backend_issuer_test.go
Labels: size/S

#2164 v4.0.0 upgrade guide
  website/docs/guides/version_4_upgrade.html.markdown
Labels: documentation, size/XL

#2188 Prepare for v4.0.0 release
  CHANGELOG.md
  website/vault.erb
Labels: documentation, size/XS

#2190 Azure Creds: Honors the documented default behavior (again)
  CHANGELOG.md
  vault/data_source_azure_access_credentials.go
  vault/data_source_azure_access_credentials_test.go
Labels: size/XS

#2198 do not require sudo perms for auth read operations
  CHANGELOG.md
  go.mod
  go.sum
  website/docs/guides/policies.html.markdown
  website/docs/guides/version_4_upgrade.html.markdown
Labels: documentation, dependencies, size/XS

#2154 Add vault_config_ui_custom_message resource
  CHANGELOG.md
  internal/consts/consts.go
  vault/provider.go
  vault/resource_config_ui_custom_message.go
  vault/resource_config_ui_custom_message_test.go
  website/docs/r/config_ui_custom_messages.html.md
  website/vault.erb
Labels: documentation, size/XL

#2200 Prepare for v4.1.0 release
  .github/workflows/build.yml
  CHANGELOG.md
  website/docs/guides/version_4_upgrade.html.markdown
Labels: documentation, size/M

#2199 docs: fix outstanding docs issues
  website/docs/d/auth_backends.html.md
  website/docs/d/azure_access_credentials.html.md
  website/docs/r/identity_oidc_client.html.md
Labels: documentation, size/XS

#2187 Add version check to `max_page_size` in LDAP Auth Backend resource
  internal/consts/consts.go
  vault/resource_ldap_auth_backend.go
  vault/resource_ldap_auth_backend_test.go
Labels: size/L

#2204 approle: handle 404 on state refresh
  CHANGELOG.md
  vault/resource_approle_auth_backend_role_secret_id.go
Labels: size/XS

#2207 allow syncing with out-of-band changes for kv v1 and v2
  CHANGELOG.md
  vault/resource_kv_secret.go
  vault/resource_kv_secret_test.go
  vault/resource_kv_secret_v2.go
  vault/resource_kv_secret_v2_test.go
Labels: size/M

#2208 add namespace data source
  CHANGELOG.md
  vault/data_source_namespace.go
  vault/data_source_namespace_test.go
  vault/provider.go
  website/docs/d/namespace.html.md
  website/vault.erb
Labels: documentation, size/XL

#2096 docs: fix error in `vault_mongodbatlas_secret_backend` and `vault_mongodbatlas_secret_role`
  website/docs/r/mongodbatlas_secret_backend.html.md
  website/docs/r/mongodbatlas_secret_role.html.md
Labels: documentation, size/XS

#2202 Update Sync Association resource to include sync metadata for all subkeys
  CHANGELOG.md
  internal/consts/consts.go
  internal/provider/schema_util.go
  internal/sync/secrets_sync.go
  vault/resource_aws_secret_backend_test.go
  vault/resource_config_ui_custom_message_test.go
  vault/resource_secrets_sync_association.go
  vault/resource_secrets_sync_association_test.go
  vault/resource_secrets_sync_aws_destination.go
  vault/resource_secrets_sync_aws_destination_test.go
  vault/resource_secrets_sync_azure_destination.go
  vault/resource_secrets_sync_azure_destination_test.go
  vault/resource_secrets_sync_config_test.go
  vault/resource_secrets_sync_gcp_destination.go
  vault/resource_secrets_sync_gcp_destination_test.go
  vault/resource_secrets_sync_gh_destination.go
  vault/resource_secrets_sync_gh_destination_test.go
  vault/resource_secrets_sync_vercel_destination.go
  vault/resource_secrets_sync_vercel_destination_test.go
  website/docs/r/secrets_sync_association.html.md
  website/docs/r/secrets_sync_aws_destination.html.md
  website/docs/r/secrets_sync_azure_destination.html.md
  website/docs/r/secrets_sync_gcp_destination.html.md
  website/docs/r/secrets_sync_gh_destination.html.md
  website/docs/r/secrets_sync_vercel_destination.html.md
Labels: documentation, size/XL

#2212 add namespaces data source
  CHANGELOG.md
  vault/data_source_namespaces.go
  vault/data_source_namespaces_test.go
  vault/provider.go
  website/docs/d/namespaces.html.md
  website/vault.erb
Labels: documentation, size/L

#2214 Prep for v4.2.0 release
  CHANGELOG.md
Labels: size/XS

#2216 docs: Update CHANGELOG.md link to upgrade guide
  CHANGELOG.md
Labels: size/XS
