Repository hashicorp/terraform-provider-vault, pull requests merged in 2024-02, with the labels that each got.

#2085 Add support for Oracle database plugin connection options
  CHANGELOG.md
  vault/resource_database_secret_backend_connection.go
  website/docs/r/database_secret_backend_connection.md
Labels: documentation, size/M, resource/database_secret

#2138 Add new WIF fields to AWS secret backend
  CHANGELOG.md
  go.mod
  go.sum
  internal/consts/consts.go
  vault/resource_aws_secret_backend.go
  vault/resource_aws_secret_backend_test.go
  website/docs/r/aws_secret_backend.html.md
Labels: documentation, dependencies, size/XL

#2140 identity/group-alias: add api client lock
  CHANGELOG.md
  vault/data_identity_entity.go
  vault/resource_identity_entity_alias.go
  vault/resource_identity_group_alias.go
  vault/resource_identity_group_alias_test.go
Labels: size/M

#2141 Prepare for v3.25.0 release
  CHANGELOG.md
Labels: size/XS

#2142 Handle out-of-band approle deletion
  CHANGELOG.md
  internal/consts/consts.go
  vault/resource_approle_auth_backend_role_secret_id.go
  vault/resource_approle_auth_backend_role_secret_id_test.go
Labels: size/L

#2146 Fix unhandled error in d/azure_access_creds
  testutil/testutil.go
  vault/data_source_azure_access_credentials.go
  vault/data_source_azure_access_credentials_test.go
Labels: bug, size/M

#2128 ldap rotation import skip parameter
  CHANGELOG.md
  internal/consts/consts.go
  vault/data_source_ldap_static_role_credentials.go
  vault/data_source_ldap_static_role_credentials_test.go
  vault/resource_ldap_secret_backend.go
  vault/resource_ldap_secret_backend_static_role.go
  vault/resource_ldap_secret_backend_static_role_test.go
  vault/resource_ldap_secret_backend_test.go
  website/docs/d/ldap_static_role_credentials.html.md
  website/docs/r/ldap_secret_backend.html.md
  website/docs/r/ldap_secret_backend_static_role.html.md
Labels: documentation, size/M

#2151 Fix documentation and remove erroneous credential parameters
  vault/data_source_ldap_static_role_credentials.go
  vault/data_source_ldap_static_role_credentials_test.go
  website/docs/d/ldap_static_role_credentials.html.md
Labels: documentation, size/S

#2139 add UUID at INFO
  CHANGELOG.md
  helper/transport.go
Labels: size/XS

#1949 feat(pki): Add resource for cluster configuration
  CHANGELOG.md
  internal/consts/consts.go
  vault/provider.go
  vault/resource_pki_secret_backend_config_cluster.go
  vault/resource_pki_secret_backend_config_cluster_test.go
  website/docs/r/pki_secret_backend_config_cluster.html.md
  website/vault.erb
Labels: documentation, size/XL

#2147 feat(pki): Add support to enable_templating in vault_pki_secret_backend_config_urls
  CHANGELOG.md
  vault/resource_pki_secret_backend_config_urls.go
  vault/resource_pki_secret_backend_config_urls_test.go
  website/docs/r/pki_secret_backend_config_urls.html.md
Labels: documentation, size/M

#2095 feat(data_source_kv_secret_v2): add the metadata version in returned values
  vault/data_source_kv_secret_v2.go
  website/docs/d/kv_secret_v2.html.md
Labels: documentation, size/XS

#2156 secrets/ldap: return error on read
  CHANGELOG.md
  vault/resource_identity_entity_test.go
  vault/resource_ldap_secret_backend_dynamic_role.go
  vault/resource_ldap_secret_backend_library_set.go
  vault/resource_ldap_secret_backend_static_role.go
Labels: size/XS

#2152 performance improvements on mount fetch
  CHANGELOG.md
  util/mountutil/mountutil.go
  util/util.go
  vault/auth_mount.go
  vault/data_source_auth_backend.go
  vault/okta.go
  vault/resource_ad_secret_backend.go
  vault/resource_auth_backend.go
  vault/resource_aws_secret_backend.go
  vault/resource_azure_secret_backend.go
  vault/resource_consul_secret_backend.go
  vault/resource_gcp_auth_backend.go
  vault/resource_gcp_secret_backend.go
  vault/resource_github_auth_backend.go
  vault/resource_jwt_auth_backend.go
  vault/resource_kmip_secret_backend.go
  vault/resource_ldap_auth_backend.go
  vault/resource_mount.go
  vault/resource_namespace.go
  vault/resource_nomad_secret_backend.go
  vault/resource_okta_auth_backend.go
  vault/resource_pki_secret_backend_cert.go
  vault/resource_pki_secret_backend_config_cluster.go
  vault/resource_pki_secret_backend_config_urls.go
  vault/resource_rabbitmq_secret_backend.go
  vault/resource_secrets_sync_association.go
  vault/resource_terraform_cloud_secret_backend.go
  vault/testhelpers_test.go
Labels: size/XL

#2160 ensure unique IDs and proper use of issuer endpoints for root sign intermediate resource
  CHANGELOG.md
  vault/resource_pki_secret_backend_intermediate_set_signed.go
  vault/resource_pki_secret_backend_root_sign_intermediate.go
Labels: size/S

#2166 mountutil: ensure all errors are returned
  util/mountutil/mountutil.go
Labels: size/XS
